// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod tests {
  use super::*;
  pub mod request_reply {
    use super::*;
    mod request_reply_request_generated;
    pub use self::request_reply_request_generated::*;
    mod request_reply_response_generated;
    pub use self::request_reply_response_generated::*;
  } // request_reply
} // tests
