// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ConnectRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ConnectRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ConnectRequest<'a> {
  type Inner = ConnectRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ConnectRequest<'a> {
  pub const VT_FROM: ::flatbuffers::VOffsetT = 4;
  pub const VT_TO: ::flatbuffers::VOffsetT = 6;
  pub const VT_REPLY_CHANNEL: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ConnectRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ConnectRequestArgs
  ) -> ::flatbuffers::WIPOffset<ConnectRequest<'bldr>> {
    let mut builder = ConnectRequestBuilder::new(_fbb);
    builder.add_reply_channel(args.reply_channel);
    builder.add_to(args.to);
    builder.add_from(args.from);
    builder.finish()
  }


  #[inline]
  pub fn from(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ConnectRequest::VT_FROM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn to(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ConnectRequest::VT_TO, Some(0)).unwrap()}
  }
  #[inline]
  pub fn reply_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ConnectRequest::VT_REPLY_CHANNEL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ConnectRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("from", Self::VT_FROM, false)?
     .visit_field::<u32>("to", Self::VT_TO, false)?
     .visit_field::<u64>("reply_channel", Self::VT_REPLY_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct ConnectRequestArgs {
    pub from: u32,
    pub to: u32,
    pub reply_channel: u64,
}
impl<'a> Default for ConnectRequestArgs {
  #[inline]
  fn default() -> Self {
    ConnectRequestArgs {
      from: 0,
      to: 0,
      reply_channel: 0,
    }
  }
}

pub struct ConnectRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ConnectRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_from(&mut self, from: u32) {
    self.fbb_.push_slot::<u32>(ConnectRequest::VT_FROM, from, 0);
  }
  #[inline]
  pub fn add_to(&mut self, to: u32) {
    self.fbb_.push_slot::<u32>(ConnectRequest::VT_TO, to, 0);
  }
  #[inline]
  pub fn add_reply_channel(&mut self, reply_channel: u64) {
    self.fbb_.push_slot::<u64>(ConnectRequest::VT_REPLY_CHANNEL, reply_channel, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ConnectRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ConnectRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ConnectRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ConnectRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ConnectRequest");
      ds.field("from", &self.from());
      ds.field("to", &self.to());
      ds.field("reply_channel", &self.reply_channel());
      ds.finish()
  }
}
