// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DirectionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Direction<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Direction<'a> {
  type Inner = Direction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Direction<'a> {
  pub const VT_SCHEMA_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_CARDINALITY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Direction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DirectionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Direction<'bldr>> {
    let mut builder = DirectionBuilder::new(_fbb);
    if let Some(x) = args.schema_id { builder.add_schema_id(x); }
    builder.add_cardinality(args.cardinality);
    builder.finish()
  }


  #[inline]
  pub fn schema_id(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Direction::VT_SCHEMA_ID, None)}
  }
  #[inline]
  pub fn cardinality(&self) -> Cardinality {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Cardinality>(Direction::VT_CARDINALITY, Some(Cardinality::Zero)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Direction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("schema_id", Self::VT_SCHEMA_ID, false)?
     .visit_field::<Cardinality>("cardinality", Self::VT_CARDINALITY, false)?
     .finish();
    Ok(())
  }
}
pub struct DirectionArgs<'a> {
    pub schema_id: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub cardinality: Cardinality,
}
impl<'a> Default for DirectionArgs<'a> {
  #[inline]
  fn default() -> Self {
    DirectionArgs {
      schema_id: None,
      cardinality: Cardinality::Zero,
    }
  }
}

pub struct DirectionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DirectionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_schema_id(&mut self, schema_id: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Direction::VT_SCHEMA_ID, schema_id);
  }
  #[inline]
  pub fn add_cardinality(&mut self, cardinality: Cardinality) {
    self.fbb_.push_slot::<Cardinality>(Direction::VT_CARDINALITY, cardinality, Cardinality::Zero);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DirectionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DirectionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Direction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Direction<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Direction");
      ds.field("schema_id", &self.schema_id());
      ds.field("cardinality", &self.cardinality());
      ds.finish()
  }
}
