// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EndpointDirectionsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EndpointDirections<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EndpointDirections<'a> {
  type Inner = EndpointDirections<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EndpointDirections<'a> {
  pub const VT_INPUT: ::flatbuffers::VOffsetT = 4;
  pub const VT_OUTPUT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EndpointDirections { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EndpointDirectionsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EndpointDirections<'bldr>> {
    let mut builder = EndpointDirectionsBuilder::new(_fbb);
    if let Some(x) = args.output { builder.add_output(x); }
    if let Some(x) = args.input { builder.add_input(x); }
    builder.finish()
  }


  #[inline]
  pub fn input(&self) -> Option<Direction<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Direction>>(EndpointDirections::VT_INPUT, None)}
  }
  #[inline]
  pub fn output(&self) -> Option<Direction<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Direction>>(EndpointDirections::VT_OUTPUT, None)}
  }
}

impl ::flatbuffers::Verifiable for EndpointDirections<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Direction>>("input", Self::VT_INPUT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Direction>>("output", Self::VT_OUTPUT, false)?
     .finish();
    Ok(())
  }
}
pub struct EndpointDirectionsArgs<'a> {
    pub input: Option<::flatbuffers::WIPOffset<Direction<'a>>>,
    pub output: Option<::flatbuffers::WIPOffset<Direction<'a>>>,
}
impl<'a> Default for EndpointDirectionsArgs<'a> {
  #[inline]
  fn default() -> Self {
    EndpointDirectionsArgs {
      input: None,
      output: None,
    }
  }
}

pub struct EndpointDirectionsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EndpointDirectionsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_input(&mut self, input: ::flatbuffers::WIPOffset<Direction<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Direction>>(EndpointDirections::VT_INPUT, input);
  }
  #[inline]
  pub fn add_output(&mut self, output: ::flatbuffers::WIPOffset<Direction<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Direction>>(EndpointDirections::VT_OUTPUT, output);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EndpointDirectionsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EndpointDirectionsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EndpointDirections<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EndpointDirections<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EndpointDirections");
      ds.field("input", &self.input());
      ds.field("output", &self.output());
      ds.finish()
  }
}
