// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum RegisterRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RegisterRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RegisterRequest<'a> {
  type Inner = RegisterRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RegisterRequest<'a> {
  pub const VT_DIRECTIONS: ::flatbuffers::VOffsetT = 4;
  pub const VT_UPDATES_CHANNEL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RegisterRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RegisterRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RegisterRequest<'bldr>> {
    let mut builder = RegisterRequestBuilder::new(_fbb);
    builder.add_updates_channel(args.updates_channel);
    if let Some(x) = args.directions { builder.add_directions(x); }
    builder.finish()
  }


  #[inline]
  pub fn directions(&self) -> Option<EndpointDirections<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<EndpointDirections>>(RegisterRequest::VT_DIRECTIONS, None)}
  }
  #[inline]
  pub fn updates_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RegisterRequest::VT_UPDATES_CHANNEL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RegisterRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<EndpointDirections>>("directions", Self::VT_DIRECTIONS, false)?
     .visit_field::<u64>("updates_channel", Self::VT_UPDATES_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct RegisterRequestArgs<'a> {
    pub directions: Option<::flatbuffers::WIPOffset<EndpointDirections<'a>>>,
    pub updates_channel: u64,
}
impl<'a> Default for RegisterRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RegisterRequestArgs {
      directions: None,
      updates_channel: 0,
    }
  }
}

pub struct RegisterRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RegisterRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_directions(&mut self, directions: ::flatbuffers::WIPOffset<EndpointDirections<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<EndpointDirections>>(RegisterRequest::VT_DIRECTIONS, directions);
  }
  #[inline]
  pub fn add_updates_channel(&mut self, updates_channel: u64) {
    self.fbb_.push_slot::<u64>(RegisterRequest::VT_UPDATES_CHANNEL, updates_channel, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RegisterRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RegisterRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RegisterRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RegisterRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RegisterRequest");
      ds.field("directions", &self.directions());
      ds.field("updates_channel", &self.updates_channel());
      ds.finish()
  }
}
