// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum RegisterResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RegisterResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RegisterResponse<'a> {
  type Inner = RegisterResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RegisterResponse<'a> {
  pub const VT_ENDPOINT_ID: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RegisterResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RegisterResponseArgs
  ) -> ::flatbuffers::WIPOffset<RegisterResponse<'bldr>> {
    let mut builder = RegisterResponseBuilder::new(_fbb);
    builder.add_endpoint_id(args.endpoint_id);
    builder.finish()
  }


  #[inline]
  pub fn endpoint_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(RegisterResponse::VT_ENDPOINT_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RegisterResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("endpoint_id", Self::VT_ENDPOINT_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct RegisterResponseArgs {
    pub endpoint_id: u32,
}
impl<'a> Default for RegisterResponseArgs {
  #[inline]
  fn default() -> Self {
    RegisterResponseArgs {
      endpoint_id: 0,
    }
  }
}

pub struct RegisterResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RegisterResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_endpoint_id(&mut self, endpoint_id: u32) {
    self.fbb_.push_slot::<u32>(RegisterResponse::VT_ENDPOINT_ID, endpoint_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RegisterResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RegisterResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RegisterResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RegisterResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RegisterResponse");
      ds.field("endpoint_id", &self.endpoint_id());
      ds.finish()
  }
}
