// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_SWITCHBOARD_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_SWITCHBOARD_PAYLOAD: u8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_SWITCHBOARD_PAYLOAD: [SwitchboardPayload; 7] = [
  SwitchboardPayload::NONE,
  SwitchboardPayload::RegisterRequest,
  SwitchboardPayload::ConnectRequest,
  SwitchboardPayload::RegisterResponse,
  SwitchboardPayload::OkResponse,
  SwitchboardPayload::ErrorResponse,
  SwitchboardPayload::WiringUpdate,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct SwitchboardPayload(pub u8);
#[allow(non_upper_case_globals)]
impl SwitchboardPayload {
  pub const NONE: Self = Self(0);
  pub const RegisterRequest: Self = Self(1);
  pub const ConnectRequest: Self = Self(2);
  pub const RegisterResponse: Self = Self(3);
  pub const OkResponse: Self = Self(4);
  pub const ErrorResponse: Self = Self(5);
  pub const WiringUpdate: Self = Self(6);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::RegisterRequest,
    Self::ConnectRequest,
    Self::RegisterResponse,
    Self::OkResponse,
    Self::ErrorResponse,
    Self::WiringUpdate,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::RegisterRequest => Some("RegisterRequest"),
      Self::ConnectRequest => Some("ConnectRequest"),
      Self::RegisterResponse => Some("RegisterResponse"),
      Self::OkResponse => Some("OkResponse"),
      Self::ErrorResponse => Some("ErrorResponse"),
      Self::WiringUpdate => Some("WiringUpdate"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for SwitchboardPayload {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for SwitchboardPayload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for SwitchboardPayload {
    type Output = SwitchboardPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for SwitchboardPayload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for SwitchboardPayload {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for SwitchboardPayload {}
pub struct SwitchboardPayloadUnionTableOffset {}

