// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum WiringUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WiringUpdate<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for WiringUpdate<'a> {
  type Inner = WiringUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> WiringUpdate<'a> {
  pub const VT_ENDPOINT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_INBOUND: ::flatbuffers::VOffsetT = 6;
  pub const VT_OUTBOUND: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    WiringUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WiringUpdateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<WiringUpdate<'bldr>> {
    let mut builder = WiringUpdateBuilder::new(_fbb);
    if let Some(x) = args.outbound { builder.add_outbound(x); }
    if let Some(x) = args.inbound { builder.add_inbound(x); }
    builder.add_endpoint_id(args.endpoint_id);
    builder.finish()
  }


  #[inline]
  pub fn endpoint_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(WiringUpdate::VT_ENDPOINT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn inbound(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringIngress<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringIngress>>>>(WiringUpdate::VT_INBOUND, None)}
  }
  #[inline]
  pub fn outbound(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringEgress<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringEgress>>>>(WiringUpdate::VT_OUTBOUND, None)}
  }
}

impl ::flatbuffers::Verifiable for WiringUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("endpoint_id", Self::VT_ENDPOINT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<WiringIngress>>>>("inbound", Self::VT_INBOUND, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<WiringEgress>>>>("outbound", Self::VT_OUTBOUND, false)?
     .finish();
    Ok(())
  }
}
pub struct WiringUpdateArgs<'a> {
    pub endpoint_id: u32,
    pub inbound: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringIngress<'a>>>>>,
    pub outbound: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<WiringEgress<'a>>>>>,
}
impl<'a> Default for WiringUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    WiringUpdateArgs {
      endpoint_id: 0,
      inbound: None,
      outbound: None,
    }
  }
}

pub struct WiringUpdateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WiringUpdateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_endpoint_id(&mut self, endpoint_id: u32) {
    self.fbb_.push_slot::<u32>(WiringUpdate::VT_ENDPOINT_ID, endpoint_id, 0);
  }
  #[inline]
  pub fn add_inbound(&mut self, inbound: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<WiringIngress<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(WiringUpdate::VT_INBOUND, inbound);
  }
  #[inline]
  pub fn add_outbound(&mut self, outbound: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<WiringEgress<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(WiringUpdate::VT_OUTBOUND, outbound);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> WiringUpdateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WiringUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<WiringUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for WiringUpdate<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("WiringUpdate");
      ds.field("endpoint_id", &self.endpoint_id());
      ds.field("inbound", &self.inbound());
      ds.field("outbound", &self.outbound());
      ds.finish()
  }
}
