// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum WiringIngressOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct WiringIngress<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for WiringIngress<'a> {
  type Inner = WiringIngress<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> WiringIngress<'a> {
  pub const VT_FROM: ::flatbuffers::VOffsetT = 4;
  pub const VT_CHANNEL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    WiringIngress { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WiringIngressArgs
  ) -> ::flatbuffers::WIPOffset<WiringIngress<'bldr>> {
    let mut builder = WiringIngressBuilder::new(_fbb);
    builder.add_channel(args.channel);
    builder.add_from(args.from);
    builder.finish()
  }


  #[inline]
  pub fn from(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(WiringIngress::VT_FROM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(WiringIngress::VT_CHANNEL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for WiringIngress<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("from", Self::VT_FROM, false)?
     .visit_field::<u64>("channel", Self::VT_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct WiringIngressArgs {
    pub from: u32,
    pub channel: u64,
}
impl<'a> Default for WiringIngressArgs {
  #[inline]
  fn default() -> Self {
    WiringIngressArgs {
      from: 0,
      channel: 0,
    }
  }
}

pub struct WiringIngressBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WiringIngressBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_from(&mut self, from: u32) {
    self.fbb_.push_slot::<u32>(WiringIngress::VT_FROM, from, 0);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: u64) {
    self.fbb_.push_slot::<u64>(WiringIngress::VT_CHANNEL, channel, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> WiringIngressBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WiringIngressBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<WiringIngress<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for WiringIngress<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("WiringIngress");
      ds.field("from", &self.from());
      ds.field("channel", &self.channel());
      ds.finish()
  }
}
