// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum AccountantControlOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AccountantControl<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AccountantControl<'a> {
  type Inner = AccountantControl<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AccountantControl<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 6;
  pub const VT_PLAN: ::flatbuffers::VOffsetT = 8;
  pub const VT_OVERAGE: ::flatbuffers::VOffsetT = 10;
  pub const VT_PROCESSES: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AccountantControl { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AccountantControlArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AccountantControl<'bldr>> {
    let mut builder = AccountantControlBuilder::new(_fbb);
    builder.add_processes(args.processes);
    if let Some(x) = args.overage { builder.add_overage(x); }
    if let Some(x) = args.plan { builder.add_plan(x); }
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(AccountantControl::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AccountantControl::VT_TENANT, None)}
  }
  #[inline]
  pub fn plan(&self) -> Option<TenantPlan<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TenantPlan>>(AccountantControl::VT_PLAN, None)}
  }
  #[inline]
  pub fn overage(&self) -> Option<TenantPlan<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<TenantPlan>>(AccountantControl::VT_OVERAGE, None)}
  }
  #[inline]
  pub fn processes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AccountantControl::VT_PROCESSES, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for AccountantControl<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<TenantPlan>>("plan", Self::VT_PLAN, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<TenantPlan>>("overage", Self::VT_OVERAGE, false)?
     .visit_field::<u64>("processes", Self::VT_PROCESSES, false)?
     .finish();
    Ok(())
  }
}
pub struct AccountantControlArgs<'a> {
    pub variant: u8,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub plan: Option<::flatbuffers::WIPOffset<TenantPlan<'a>>>,
    pub overage: Option<::flatbuffers::WIPOffset<TenantPlan<'a>>>,
    pub processes: u64,
}
impl<'a> Default for AccountantControlArgs<'a> {
  #[inline]
  fn default() -> Self {
    AccountantControlArgs {
      variant: 0,
      tenant: None,
      plan: None,
      overage: None,
      processes: 0,
    }
  }
}

pub struct AccountantControlBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AccountantControlBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(AccountantControl::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AccountantControl::VT_TENANT, tenant);
  }
  #[inline]
  pub fn add_plan(&mut self, plan: ::flatbuffers::WIPOffset<TenantPlan<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<TenantPlan>>(AccountantControl::VT_PLAN, plan);
  }
  #[inline]
  pub fn add_overage(&mut self, overage: ::flatbuffers::WIPOffset<TenantPlan<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<TenantPlan>>(AccountantControl::VT_OVERAGE, overage);
  }
  #[inline]
  pub fn add_processes(&mut self, processes: u64) {
    self.fbb_.push_slot::<u64>(AccountantControl::VT_PROCESSES, processes, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AccountantControlBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AccountantControlBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AccountantControl<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AccountantControl<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AccountantControl");
      ds.field("variant", &self.variant());
      ds.field("tenant", &self.tenant());
      ds.field("plan", &self.plan());
      ds.field("overage", &self.overage());
      ds.field("processes", &self.processes());
      ds.finish()
  }
}
