// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum AccountantControlResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AccountantControlResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AccountantControlResponse<'a> {
  type Inner = AccountantControlResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AccountantControlResponse<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 6;
  pub const VT_CONTEXT: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AccountantControlResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AccountantControlResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AccountantControlResponse<'bldr>> {
    let mut builder = AccountantControlResponseBuilder::new(_fbb);
    if let Some(x) = args.context { builder.add_context(x); }
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(AccountantControlResponse::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AccountantControlResponse::VT_TENANT, None)}
  }
  #[inline]
  pub fn context(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AccountantControlResponse::VT_CONTEXT, None)}
  }
}

impl ::flatbuffers::Verifiable for AccountantControlResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("context", Self::VT_CONTEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct AccountantControlResponseArgs<'a> {
    pub variant: u8,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub context: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for AccountantControlResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    AccountantControlResponseArgs {
      variant: 0,
      tenant: None,
      context: None,
    }
  }
}

pub struct AccountantControlResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AccountantControlResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(AccountantControlResponse::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AccountantControlResponse::VT_TENANT, tenant);
  }
  #[inline]
  pub fn add_context(&mut self, context: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AccountantControlResponse::VT_CONTEXT, context);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AccountantControlResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AccountantControlResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AccountantControlResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AccountantControlResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AccountantControlResponse");
      ds.field("variant", &self.variant());
      ds.field("tenant", &self.tenant());
      ds.field("context", &self.context());
      ds.finish()
  }
}
