// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum MeteringBucketOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MeteringBucket<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for MeteringBucket<'a> {
  type Inner = MeteringBucket<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MeteringBucket<'a> {
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_CPU_INSTRUCTIONS: ::flatbuffers::VOffsetT = 6;
  pub const VT_MEMORY_BYTES: ::flatbuffers::VOffsetT = 8;
  pub const VT_STORAGE_BYTES: ::flatbuffers::VOffsetT = 10;
  pub const VT_BANDWIDTH_BYTES: ::flatbuffers::VOffsetT = 12;
  pub const VT_PUBLISHED_UNIX_S: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    MeteringBucket { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MeteringBucketArgs<'args>
  ) -> ::flatbuffers::WIPOffset<MeteringBucket<'bldr>> {
    let mut builder = MeteringBucketBuilder::new(_fbb);
    builder.add_published_unix_s(args.published_unix_s);
    builder.add_bandwidth_bytes(args.bandwidth_bytes);
    builder.add_storage_bytes(args.storage_bytes);
    builder.add_memory_bytes(args.memory_bytes);
    builder.add_cpu_instructions(args.cpu_instructions);
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    builder.finish()
  }


  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(MeteringBucket::VT_TENANT, None)}
  }
  #[inline]
  pub fn cpu_instructions(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MeteringBucket::VT_CPU_INSTRUCTIONS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn memory_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MeteringBucket::VT_MEMORY_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn storage_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MeteringBucket::VT_STORAGE_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn bandwidth_bytes(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MeteringBucket::VT_BANDWIDTH_BYTES, Some(0)).unwrap()}
  }
  #[inline]
  pub fn published_unix_s(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(MeteringBucket::VT_PUBLISHED_UNIX_S, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for MeteringBucket<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .visit_field::<u64>("cpu_instructions", Self::VT_CPU_INSTRUCTIONS, false)?
     .visit_field::<u64>("memory_bytes", Self::VT_MEMORY_BYTES, false)?
     .visit_field::<u64>("storage_bytes", Self::VT_STORAGE_BYTES, false)?
     .visit_field::<u64>("bandwidth_bytes", Self::VT_BANDWIDTH_BYTES, false)?
     .visit_field::<u64>("published_unix_s", Self::VT_PUBLISHED_UNIX_S, false)?
     .finish();
    Ok(())
  }
}
pub struct MeteringBucketArgs<'a> {
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub cpu_instructions: u64,
    pub memory_bytes: u64,
    pub storage_bytes: u64,
    pub bandwidth_bytes: u64,
    pub published_unix_s: u64,
}
impl<'a> Default for MeteringBucketArgs<'a> {
  #[inline]
  fn default() -> Self {
    MeteringBucketArgs {
      tenant: None,
      cpu_instructions: 0,
      memory_bytes: 0,
      storage_bytes: 0,
      bandwidth_bytes: 0,
      published_unix_s: 0,
    }
  }
}

pub struct MeteringBucketBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MeteringBucketBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MeteringBucket::VT_TENANT, tenant);
  }
  #[inline]
  pub fn add_cpu_instructions(&mut self, cpu_instructions: u64) {
    self.fbb_.push_slot::<u64>(MeteringBucket::VT_CPU_INSTRUCTIONS, cpu_instructions, 0);
  }
  #[inline]
  pub fn add_memory_bytes(&mut self, memory_bytes: u64) {
    self.fbb_.push_slot::<u64>(MeteringBucket::VT_MEMORY_BYTES, memory_bytes, 0);
  }
  #[inline]
  pub fn add_storage_bytes(&mut self, storage_bytes: u64) {
    self.fbb_.push_slot::<u64>(MeteringBucket::VT_STORAGE_BYTES, storage_bytes, 0);
  }
  #[inline]
  pub fn add_bandwidth_bytes(&mut self, bandwidth_bytes: u64) {
    self.fbb_.push_slot::<u64>(MeteringBucket::VT_BANDWIDTH_BYTES, bandwidth_bytes, 0);
  }
  #[inline]
  pub fn add_published_unix_s(&mut self, published_unix_s: u64) {
    self.fbb_.push_slot::<u64>(MeteringBucket::VT_PUBLISHED_UNIX_S, published_unix_s, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MeteringBucketBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MeteringBucketBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<MeteringBucket<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for MeteringBucket<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("MeteringBucket");
      ds.field("tenant", &self.tenant());
      ds.field("cpu_instructions", &self.cpu_instructions());
      ds.field("memory_bytes", &self.memory_bytes());
      ds.field("storage_bytes", &self.storage_bytes());
      ds.field("bandwidth_bytes", &self.bandwidth_bytes());
      ds.field("published_unix_s", &self.published_unix_s());
      ds.finish()
  }
}

#[inline]
/// Verifies that a buffer of bytes contains a `MeteringBucket`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metering_bucket_unchecked`.
pub fn root_as_metering_bucket(buf: &[u8]) -> Result<MeteringBucket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<MeteringBucket>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `MeteringBucket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_metering_bucket_unchecked`.
pub fn size_prefixed_root_as_metering_bucket(buf: &[u8]) -> Result<MeteringBucket<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<MeteringBucket>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `MeteringBucket` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metering_bucket_unchecked`.
pub fn root_as_metering_bucket_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MeteringBucket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<MeteringBucket<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `MeteringBucket` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metering_bucket_unchecked`.
pub fn size_prefixed_root_as_metering_bucket_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<MeteringBucket<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<MeteringBucket<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a MeteringBucket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `MeteringBucket`.
pub unsafe fn root_as_metering_bucket_unchecked(buf: &[u8]) -> MeteringBucket<'_> {
  unsafe { ::flatbuffers::root_unchecked::<MeteringBucket>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed MeteringBucket and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `MeteringBucket`.
pub unsafe fn size_prefixed_root_as_metering_bucket_unchecked(buf: &[u8]) -> MeteringBucket<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<MeteringBucket>(buf) }
}
#[inline]
pub fn finish_metering_bucket_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<MeteringBucket<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_metering_bucket_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<MeteringBucket<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
