// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod examples {
  use super::*;
  pub mod log_analyser {
    use super::*;
    mod warning_generated;
    pub use self::warning_generated::*;
  } // log_analyser
} // examples
