// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum AtlasMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AtlasMessage<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AtlasMessage<'a> {
  type Inner = AtlasMessage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AtlasMessage<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_PAYLOAD_TYPE: ::flatbuffers::VOffsetT = 6;
  pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AtlasMessage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AtlasMessageArgs
  ) -> ::flatbuffers::WIPOffset<AtlasMessage<'bldr>> {
    let mut builder = AtlasMessageBuilder::new(_fbb);
    builder.add_request_id(args.request_id);
    if let Some(x) = args.payload { builder.add_payload(x); }
    builder.add_payload_type(args.payload_type);
    builder.finish()
  }


  #[inline]
  pub fn request_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AtlasMessage::VT_REQUEST_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn payload_type(&self) -> AtlasPayload {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<AtlasPayload>(AtlasMessage::VT_PAYLOAD_TYPE, Some(AtlasPayload::NONE)).unwrap()}
  }
  #[inline]
  pub fn payload(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(AtlasMessage::VT_PAYLOAD, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_get_request(&self) -> Option<GetRequest<'a>> {
    if self.payload_type() == AtlasPayload::GetRequest {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { GetRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_insert_request(&self) -> Option<InsertRequest<'a>> {
    if self.payload_type() == AtlasPayload::InsertRequest {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { InsertRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_remove_request(&self) -> Option<RemoveRequest<'a>> {
    if self.payload_type() == AtlasPayload::RemoveRequest {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RemoveRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_lookup_request(&self) -> Option<LookupRequest<'a>> {
    if self.payload_type() == AtlasPayload::LookupRequest {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { LookupRequest::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_get_response(&self) -> Option<GetResponse<'a>> {
    if self.payload_type() == AtlasPayload::GetResponse {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { GetResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_remove_response(&self) -> Option<RemoveResponse<'a>> {
    if self.payload_type() == AtlasPayload::RemoveResponse {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { RemoveResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_lookup_response(&self) -> Option<LookupResponse<'a>> {
    if self.payload_type() == AtlasPayload::LookupResponse {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { LookupResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_ok_response(&self) -> Option<OkResponse<'a>> {
    if self.payload_type() == AtlasPayload::OkResponse {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { OkResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn payload_as_error_response(&self) -> Option<ErrorResponse<'a>> {
    if self.payload_type() == AtlasPayload::ErrorResponse {
      self.payload().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ErrorResponse::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for AtlasMessage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_union::<AtlasPayload, _>("payload_type", Self::VT_PAYLOAD_TYPE, "payload", Self::VT_PAYLOAD, false, |key, v, pos| {
        match key {
          AtlasPayload::GetRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<GetRequest>>("AtlasPayload::GetRequest", pos),
          AtlasPayload::InsertRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<InsertRequest>>("AtlasPayload::InsertRequest", pos),
          AtlasPayload::RemoveRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<RemoveRequest>>("AtlasPayload::RemoveRequest", pos),
          AtlasPayload::LookupRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<LookupRequest>>("AtlasPayload::LookupRequest", pos),
          AtlasPayload::GetResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<GetResponse>>("AtlasPayload::GetResponse", pos),
          AtlasPayload::RemoveResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<RemoveResponse>>("AtlasPayload::RemoveResponse", pos),
          AtlasPayload::LookupResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<LookupResponse>>("AtlasPayload::LookupResponse", pos),
          AtlasPayload::OkResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<OkResponse>>("AtlasPayload::OkResponse", pos),
          AtlasPayload::ErrorResponse => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ErrorResponse>>("AtlasPayload::ErrorResponse", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct AtlasMessageArgs {
    pub request_id: u64,
    pub payload_type: AtlasPayload,
    pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for AtlasMessageArgs {
  #[inline]
  fn default() -> Self {
    AtlasMessageArgs {
      request_id: 0,
      payload_type: AtlasPayload::NONE,
      payload: None,
    }
  }
}

pub struct AtlasMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AtlasMessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: u64) {
    self.fbb_.push_slot::<u64>(AtlasMessage::VT_REQUEST_ID, request_id, 0);
  }
  #[inline]
  pub fn add_payload_type(&mut self, payload_type: AtlasPayload) {
    self.fbb_.push_slot::<AtlasPayload>(AtlasMessage::VT_PAYLOAD_TYPE, payload_type, AtlasPayload::NONE);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AtlasMessage::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AtlasMessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AtlasMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AtlasMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AtlasMessage<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AtlasMessage");
      ds.field("request_id", &self.request_id());
      ds.field("payload_type", &self.payload_type());
      match self.payload_type() {
        AtlasPayload::GetRequest => {
          if let Some(x) = self.payload_as_get_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::InsertRequest => {
          if let Some(x) = self.payload_as_insert_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::RemoveRequest => {
          if let Some(x) = self.payload_as_remove_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::LookupRequest => {
          if let Some(x) = self.payload_as_lookup_request() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::GetResponse => {
          if let Some(x) = self.payload_as_get_response() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::RemoveResponse => {
          if let Some(x) = self.payload_as_remove_response() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::LookupResponse => {
          if let Some(x) = self.payload_as_lookup_response() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::OkResponse => {
          if let Some(x) = self.payload_as_ok_response() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        AtlasPayload::ErrorResponse => {
          if let Some(x) = self.payload_as_error_response() {
            ds.field("payload", &x)
          } else {
            ds.field("payload", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("payload", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `AtlasMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_atlas_message_unchecked`.
pub fn root_as_atlas_message(buf: &[u8]) -> Result<AtlasMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<AtlasMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `AtlasMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_atlas_message_unchecked`.
pub fn size_prefixed_root_as_atlas_message(buf: &[u8]) -> Result<AtlasMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<AtlasMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `AtlasMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_atlas_message_unchecked`.
pub fn root_as_atlas_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<AtlasMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<AtlasMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `AtlasMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_atlas_message_unchecked`.
pub fn size_prefixed_root_as_atlas_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<AtlasMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<AtlasMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a AtlasMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `AtlasMessage`.
pub unsafe fn root_as_atlas_message_unchecked(buf: &[u8]) -> AtlasMessage<'_> {
  unsafe { ::flatbuffers::root_unchecked::<AtlasMessage>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed AtlasMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `AtlasMessage`.
pub unsafe fn size_prefixed_root_as_atlas_message_unchecked(buf: &[u8]) -> AtlasMessage<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<AtlasMessage>(buf) }
}
pub const ATLAS_MESSAGE_IDENTIFIER: &str = "ATLS";

#[inline]
pub fn atlas_message_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ATLAS_MESSAGE_IDENTIFIER, false)
}

#[inline]
pub fn atlas_message_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ATLAS_MESSAGE_IDENTIFIER, true)
}

#[inline]
pub fn finish_atlas_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<AtlasMessage<'a>>) {
  fbb.finish(root, Some(ATLAS_MESSAGE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_atlas_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<AtlasMessage<'a>>) {
  fbb.finish_size_prefixed(root, Some(ATLAS_MESSAGE_IDENTIFIER));
}
