// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ATLAS_PAYLOAD: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ATLAS_PAYLOAD: u8 = 9;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ATLAS_PAYLOAD: [AtlasPayload; 10] = [
  AtlasPayload::NONE,
  AtlasPayload::GetRequest,
  AtlasPayload::InsertRequest,
  AtlasPayload::RemoveRequest,
  AtlasPayload::LookupRequest,
  AtlasPayload::GetResponse,
  AtlasPayload::RemoveResponse,
  AtlasPayload::LookupResponse,
  AtlasPayload::OkResponse,
  AtlasPayload::ErrorResponse,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct AtlasPayload(pub u8);
#[allow(non_upper_case_globals)]
impl AtlasPayload {
  pub const NONE: Self = Self(0);
  pub const GetRequest: Self = Self(1);
  pub const InsertRequest: Self = Self(2);
  pub const RemoveRequest: Self = Self(3);
  pub const LookupRequest: Self = Self(4);
  pub const GetResponse: Self = Self(5);
  pub const RemoveResponse: Self = Self(6);
  pub const LookupResponse: Self = Self(7);
  pub const OkResponse: Self = Self(8);
  pub const ErrorResponse: Self = Self(9);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 9;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::GetRequest,
    Self::InsertRequest,
    Self::RemoveRequest,
    Self::LookupRequest,
    Self::GetResponse,
    Self::RemoveResponse,
    Self::LookupResponse,
    Self::OkResponse,
    Self::ErrorResponse,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::GetRequest => Some("GetRequest"),
      Self::InsertRequest => Some("InsertRequest"),
      Self::RemoveRequest => Some("RemoveRequest"),
      Self::LookupRequest => Some("LookupRequest"),
      Self::GetResponse => Some("GetResponse"),
      Self::RemoveResponse => Some("RemoveResponse"),
      Self::LookupResponse => Some("LookupResponse"),
      Self::OkResponse => Some("OkResponse"),
      Self::ErrorResponse => Some("ErrorResponse"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for AtlasPayload {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for AtlasPayload {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for AtlasPayload {
    type Output = AtlasPayload;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for AtlasPayload {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for AtlasPayload {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for AtlasPayload {}
pub struct AtlasPayloadUnionTableOffset {}

