// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum GetResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetResponse<'a> {
  type Inner = GetResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetResponse<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_FOUND: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GetResponseArgs
  ) -> ::flatbuffers::WIPOffset<GetResponse<'bldr>> {
    let mut builder = GetResponseBuilder::new(_fbb);
    builder.add_id(args.id);
    builder.add_found(args.found);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(GetResponse::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn found(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(GetResponse::VT_FOUND, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for GetResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<bool>("found", Self::VT_FOUND, false)?
     .finish();
    Ok(())
  }
}
pub struct GetResponseArgs {
    pub id: u64,
    pub found: bool,
}
impl<'a> Default for GetResponseArgs {
  #[inline]
  fn default() -> Self {
    GetResponseArgs {
      id: 0,
      found: false,
    }
  }
}

pub struct GetResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(GetResponse::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_found(&mut self, found: bool) {
    self.fbb_.push_slot::<bool>(GetResponse::VT_FOUND, found, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetResponse");
      ds.field("id", &self.id());
      ds.field("found", &self.found());
      ds.finish()
  }
}
