// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum LookupResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LookupResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LookupResponse<'a> {
  type Inner = LookupResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LookupResponse<'a> {
  pub const VT_IDS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LookupResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LookupResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LookupResponse<'bldr>> {
    let mut builder = LookupResponseBuilder::new(_fbb);
    if let Some(x) = args.ids { builder.add_ids(x); }
    builder.finish()
  }


  #[inline]
  pub fn ids(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(LookupResponse::VT_IDS, None)}
  }
}

impl ::flatbuffers::Verifiable for LookupResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("ids", Self::VT_IDS, false)?
     .finish();
    Ok(())
  }
}
pub struct LookupResponseArgs<'a> {
    pub ids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
}
impl<'a> Default for LookupResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    LookupResponseArgs {
      ids: None,
    }
  }
}

pub struct LookupResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LookupResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ids(&mut self, ids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LookupResponse::VT_IDS, ids);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LookupResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LookupResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LookupResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LookupResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LookupResponse");
      ds.field("ids", &self.ids());
      ds.finish()
  }
}
