// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum LookupRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LookupRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LookupRequest<'a> {
  type Inner = LookupRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LookupRequest<'a> {
  pub const VT_PATTERN: ::flatbuffers::VOffsetT = 4;
  pub const VT_REPLY_CHANNEL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LookupRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LookupRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LookupRequest<'bldr>> {
    let mut builder = LookupRequestBuilder::new(_fbb);
    builder.add_reply_channel(args.reply_channel);
    if let Some(x) = args.pattern { builder.add_pattern(x); }
    builder.finish()
  }


  #[inline]
  pub fn pattern(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LookupRequest::VT_PATTERN, None)}
  }
  #[inline]
  pub fn reply_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(LookupRequest::VT_REPLY_CHANNEL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for LookupRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("pattern", Self::VT_PATTERN, false)?
     .visit_field::<u64>("reply_channel", Self::VT_REPLY_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct LookupRequestArgs<'a> {
    pub pattern: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub reply_channel: u64,
}
impl<'a> Default for LookupRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    LookupRequestArgs {
      pattern: None,
      reply_channel: 0,
    }
  }
}

pub struct LookupRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LookupRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_pattern(&mut self, pattern: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LookupRequest::VT_PATTERN, pattern);
  }
  #[inline]
  pub fn add_reply_channel(&mut self, reply_channel: u64) {
    self.fbb_.push_slot::<u64>(LookupRequest::VT_REPLY_CHANNEL, reply_channel, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LookupRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LookupRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LookupRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LookupRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LookupRequest");
      ds.field("pattern", &self.pattern());
      ds.field("reply_channel", &self.reply_channel());
      ds.finish()
  }
}
