// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum RemoveRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RemoveRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RemoveRequest<'a> {
  type Inner = RemoveRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RemoveRequest<'a> {
  pub const VT_URI: ::flatbuffers::VOffsetT = 4;
  pub const VT_REPLY_CHANNEL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RemoveRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RemoveRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RemoveRequest<'bldr>> {
    let mut builder = RemoveRequestBuilder::new(_fbb);
    builder.add_reply_channel(args.reply_channel);
    if let Some(x) = args.uri { builder.add_uri(x); }
    builder.finish()
  }


  #[inline]
  pub fn uri(&self) -> Option<super::uri::Uri<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<super::uri::Uri>>(RemoveRequest::VT_URI, None)}
  }
  #[inline]
  pub fn reply_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(RemoveRequest::VT_REPLY_CHANNEL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for RemoveRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<super::uri::Uri>>("uri", Self::VT_URI, false)?
     .visit_field::<u64>("reply_channel", Self::VT_REPLY_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct RemoveRequestArgs<'a> {
    pub uri: Option<::flatbuffers::WIPOffset<super::uri::Uri<'a>>>,
    pub reply_channel: u64,
}
impl<'a> Default for RemoveRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    RemoveRequestArgs {
      uri: None,
      reply_channel: 0,
    }
  }
}

pub struct RemoveRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RemoveRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<super::uri::Uri<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<super::uri::Uri>>(RemoveRequest::VT_URI, uri);
  }
  #[inline]
  pub fn add_reply_channel(&mut self, reply_channel: u64) {
    self.fbb_.push_slot::<u64>(RemoveRequest::VT_REPLY_CHANNEL, reply_channel, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RemoveRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RemoveRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RemoveRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RemoveRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RemoveRequest");
      ds.field("uri", &self.uri());
      ds.field("reply_channel", &self.reply_channel());
      ds.finish()
  }
}
