// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod examples {
  use super::*;
  pub mod edge_waf {
    use super::*;
    mod http_request_meta_generated;
    pub use self::http_request_meta_generated::*;
    mod verdict_generated;
    pub use self::verdict_generated::*;
    mod security_alert_generated;
    pub use self::security_alert_generated::*;
    mod audit_record_generated;
    pub use self::audit_record_generated::*;
  } // edge_waf
} // examples
