// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for Selium Flatbuffers namespaces.
pub mod selium {
  use super::*;
  pub mod switchboard {
    use super::*;
    mod cardinality_generated;
    pub use self::cardinality_generated::*;
    mod connect_request_generated;
    pub use self::connect_request_generated::*;
    mod direction_generated;
    pub use self::direction_generated::*;
    mod endpoint_directions_generated;
    pub use self::endpoint_directions_generated::*;
    mod error_response_generated;
    pub use self::error_response_generated::*;
    mod ok_response_generated;
    pub use self::ok_response_generated::*;
    mod register_request_generated;
    pub use self::register_request_generated::*;
    mod register_response_generated;
    pub use self::register_response_generated::*;
    mod switchboard_message_generated;
    pub use self::switchboard_message_generated::*;
    mod switchboard_payload_generated;
    pub use self::switchboard_payload_generated::*;
    mod wiring_egress_generated;
    pub use self::wiring_egress_generated::*;
    mod wiring_ingress_generated;
    pub use self::wiring_ingress_generated::*;
    mod wiring_update_generated;
    pub use self::wiring_update_generated::*;
  }
}
