// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum NetConnectionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NetConnection<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for NetConnection<'a> {
  type Inner = NetConnection<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NetConnection<'a> {
  pub const VT_READER: ::flatbuffers::VOffsetT = 4;
  pub const VT_WRITER: ::flatbuffers::VOffsetT = 6;
  pub const VT_REMOTE_ADDR: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    NetConnection { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NetConnectionArgs<'args>
  ) -> ::flatbuffers::WIPOffset<NetConnection<'bldr>> {
    let mut builder = NetConnectionBuilder::new(_fbb);
    if let Some(x) = args.remote_addr { builder.add_remote_addr(x); }
    if let Some(x) = args.writer { builder.add_writer(x); }
    if let Some(x) = args.reader { builder.add_reader(x); }
    builder.finish()
  }


  #[inline]
  pub fn reader(&self) -> Option<NetReader<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<NetReader>>(NetConnection::VT_READER, None)}
  }
  #[inline]
  pub fn writer(&self) -> Option<NetWriter<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<NetWriter>>(NetConnection::VT_WRITER, None)}
  }
  #[inline]
  pub fn remote_addr(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(NetConnection::VT_REMOTE_ADDR, None)}
  }
}

impl ::flatbuffers::Verifiable for NetConnection<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<NetReader>>("reader", Self::VT_READER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<NetWriter>>("writer", Self::VT_WRITER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("remote_addr", Self::VT_REMOTE_ADDR, false)?
     .finish();
    Ok(())
  }
}
pub struct NetConnectionArgs<'a> {
    pub reader: Option<::flatbuffers::WIPOffset<NetReader<'a>>>,
    pub writer: Option<::flatbuffers::WIPOffset<NetWriter<'a>>>,
    pub remote_addr: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for NetConnectionArgs<'a> {
  #[inline]
  fn default() -> Self {
    NetConnectionArgs {
      reader: None,
      writer: None,
      remote_addr: None,
    }
  }
}

pub struct NetConnectionBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> NetConnectionBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_reader(&mut self, reader: ::flatbuffers::WIPOffset<NetReader<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<NetReader>>(NetConnection::VT_READER, reader);
  }
  #[inline]
  pub fn add_writer(&mut self, writer: ::flatbuffers::WIPOffset<NetWriter<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<NetWriter>>(NetConnection::VT_WRITER, writer);
  }
  #[inline]
  pub fn add_remote_addr(&mut self, remote_addr: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(NetConnection::VT_REMOTE_ADDR, remote_addr);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> NetConnectionBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NetConnectionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<NetConnection<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for NetConnection<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("NetConnection");
      ds.field("reader", &self.reader());
      ds.field("writer", &self.writer());
      ds.field("remote_addr", &self.remote_addr());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `NetConnection`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_net_connection_unchecked`.
pub fn root_as_net_connection(buf: &[u8]) -> Result<NetConnection<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<NetConnection>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `NetConnection` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_net_connection_unchecked`.
pub fn size_prefixed_root_as_net_connection(buf: &[u8]) -> Result<NetConnection<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<NetConnection>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `NetConnection` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_net_connection_unchecked`.
pub fn root_as_net_connection_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NetConnection<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<NetConnection<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `NetConnection` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_net_connection_unchecked`.
pub fn size_prefixed_root_as_net_connection_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NetConnection<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<NetConnection<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a NetConnection and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `NetConnection`.
pub unsafe fn root_as_net_connection_unchecked(buf: &[u8]) -> NetConnection<'_> {
  unsafe { ::flatbuffers::root_unchecked::<NetConnection>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed NetConnection and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `NetConnection`.
pub unsafe fn size_prefixed_root_as_net_connection_unchecked(buf: &[u8]) -> NetConnection<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<NetConnection>(buf) }
}
pub const NET_CONNECTION_IDENTIFIER: &str = "SNET";

#[inline]
pub fn net_connection_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, NET_CONNECTION_IDENTIFIER, false)
}

#[inline]
pub fn net_connection_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, NET_CONNECTION_IDENTIFIER, true)
}

#[inline]
pub fn finish_net_connection_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<NetConnection<'a>>) {
  fbb.finish(root, Some(NET_CONNECTION_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_net_connection_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<NetConnection<'a>>) {
  fbb.finish_size_prefixed(root, Some(NET_CONNECTION_IDENTIFIER));
}
