// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum NetWriterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NetWriter<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for NetWriter<'a> {
  type Inner = NetWriter<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NetWriter<'a> {
  pub const VT_SHARED_HANDLE: ::flatbuffers::VOffsetT = 4;
  pub const VT_PROTOCOL: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    NetWriter { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NetWriterArgs
  ) -> ::flatbuffers::WIPOffset<NetWriter<'bldr>> {
    let mut builder = NetWriterBuilder::new(_fbb);
    builder.add_shared_handle(args.shared_handle);
    builder.add_protocol(args.protocol);
    builder.finish()
  }


  #[inline]
  pub fn shared_handle(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(NetWriter::VT_SHARED_HANDLE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn protocol(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(NetWriter::VT_PROTOCOL, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for NetWriter<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("shared_handle", Self::VT_SHARED_HANDLE, false)?
     .visit_field::<u8>("protocol", Self::VT_PROTOCOL, false)?
     .finish();
    Ok(())
  }
}
pub struct NetWriterArgs {
    pub shared_handle: u64,
    pub protocol: u8,
}
impl<'a> Default for NetWriterArgs {
  #[inline]
  fn default() -> Self {
    NetWriterArgs {
      shared_handle: 0,
      protocol: 0,
    }
  }
}

pub struct NetWriterBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> NetWriterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_shared_handle(&mut self, shared_handle: u64) {
    self.fbb_.push_slot::<u64>(NetWriter::VT_SHARED_HANDLE, shared_handle, 0);
  }
  #[inline]
  pub fn add_protocol(&mut self, protocol: u8) {
    self.fbb_.push_slot::<u8>(NetWriter::VT_PROTOCOL, protocol, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> NetWriterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NetWriterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<NetWriter<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for NetWriter<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("NetWriter");
      ds.field("shared_handle", &self.shared_handle());
      ds.field("protocol", &self.protocol());
      ds.finish()
  }
}
