// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod examples {
  use super::*;
  pub mod orchestrator {
    use super::*;
    mod config_update_generated;
    pub use self::config_update_generated::*;
    mod work_item_generated;
    pub use self::work_item_generated::*;
    mod work_result_generated;
    pub use self::work_result_generated::*;
  } // orchestrator
} // examples
