// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ConfigUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Configuration updates broadcast to workers.
pub struct ConfigUpdate<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ConfigUpdate<'a> {
  type Inner = ConfigUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ConfigUpdate<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_MULTIPLIER: ::flatbuffers::VOffsetT = 6;
  pub const VT_NOTE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ConfigUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ConfigUpdateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ConfigUpdate<'bldr>> {
    let mut builder = ConfigUpdateBuilder::new(_fbb);
    if let Some(x) = args.note { builder.add_note(x); }
    builder.add_multiplier(args.multiplier);
    builder.add_version(args.version);
    builder.finish()
  }


  /// Configuration version.
  #[inline]
  pub fn version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ConfigUpdate::VT_VERSION, Some(0)).unwrap()}
  }
  /// Multiplier applied to each payload.
  #[inline]
  pub fn multiplier(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ConfigUpdate::VT_MULTIPLIER, Some(0)).unwrap()}
  }
  /// Human-readable note.
  #[inline]
  pub fn note(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ConfigUpdate::VT_NOTE, None)}
  }
}

impl ::flatbuffers::Verifiable for ConfigUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("version", Self::VT_VERSION, false)?
     .visit_field::<u32>("multiplier", Self::VT_MULTIPLIER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("note", Self::VT_NOTE, false)?
     .finish();
    Ok(())
  }
}
pub struct ConfigUpdateArgs<'a> {
    pub version: u32,
    pub multiplier: u32,
    pub note: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ConfigUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    ConfigUpdateArgs {
      version: 0,
      multiplier: 0,
      note: None,
    }
  }
}

pub struct ConfigUpdateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ConfigUpdateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u32) {
    self.fbb_.push_slot::<u32>(ConfigUpdate::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_multiplier(&mut self, multiplier: u32) {
    self.fbb_.push_slot::<u32>(ConfigUpdate::VT_MULTIPLIER, multiplier, 0);
  }
  #[inline]
  pub fn add_note(&mut self, note: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ConfigUpdate::VT_NOTE, note);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ConfigUpdateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ConfigUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ConfigUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ConfigUpdate<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ConfigUpdate");
      ds.field("version", &self.version());
      ds.field("multiplier", &self.multiplier());
      ds.field("note", &self.note());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ConfigUpdate`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_config_update_unchecked`.
pub fn root_as_config_update(buf: &[u8]) -> Result<ConfigUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ConfigUpdate>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ConfigUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_config_update_unchecked`.
pub fn size_prefixed_root_as_config_update(buf: &[u8]) -> Result<ConfigUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ConfigUpdate>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ConfigUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_config_update_unchecked`.
pub fn root_as_config_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ConfigUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ConfigUpdate<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ConfigUpdate` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_config_update_unchecked`.
pub fn size_prefixed_root_as_config_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ConfigUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ConfigUpdate<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ConfigUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ConfigUpdate`.
pub unsafe fn root_as_config_update_unchecked(buf: &[u8]) -> ConfigUpdate<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ConfigUpdate>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ConfigUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ConfigUpdate`.
pub unsafe fn size_prefixed_root_as_config_update_unchecked(buf: &[u8]) -> ConfigUpdate<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ConfigUpdate>(buf) }
}
pub const CONFIG_UPDATE_IDENTIFIER: &str = "ORCH";

#[inline]
pub fn config_update_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, CONFIG_UPDATE_IDENTIFIER, false)
}

#[inline]
pub fn config_update_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, CONFIG_UPDATE_IDENTIFIER, true)
}

#[inline]
pub fn finish_config_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ConfigUpdate<'a>>) {
  fbb.finish(root, Some(CONFIG_UPDATE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_config_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ConfigUpdate<'a>>) {
  fbb.finish_size_prefixed(root, Some(CONFIG_UPDATE_IDENTIFIER));
}
