[package]
name = "selium-discovery"
version.workspace = true
edition.workspace = true
description = "Selium discovery system guest"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true, features = ["std"] }
selium-abi.workspace = true
selium-guest.workspace = true
selium-service.workspace = true
selium-shm.workspace = true
selium-wire.workspace = true

[lints]
workspace = true
