// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum LiveTableMessageOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A table mutation published over a pub/sub topic.
///
/// Every `set` or `delete` publishes one of these messages. All processes
/// attached to the same topic replay the stream to build their local
/// materialised view.
pub struct LiveTableMessage<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LiveTableMessage<'a> {
  type Inner = LiveTableMessage<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LiveTableMessage<'a> {
  pub const VT_MUTATION_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY_BYTES: ::flatbuffers::VOffsetT = 6;
  pub const VT_VALUE_BYTES: ::flatbuffers::VOffsetT = 8;
  pub const VT_EXPECTED_VERSION: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LiveTableMessage { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LiveTableMessageArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LiveTableMessage<'bldr>> {
    let mut builder = LiveTableMessageBuilder::new(_fbb);
    builder.add_expected_version(args.expected_version);
    builder.add_mutation_id(args.mutation_id);
    if let Some(x) = args.value_bytes { builder.add_value_bytes(x); }
    if let Some(x) = args.key_bytes { builder.add_key_bytes(x); }
    builder.finish()
  }


  /// Topic-wide mutation id used to acknowledge writes in stream order.
  #[inline]
  pub fn mutation_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(LiveTableMessage::VT_MUTATION_ID, Some(0)).unwrap()}
  }
  /// The entry key encoded as bytes via FlatMsg.
  #[inline]
  pub fn key_bytes(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(LiveTableMessage::VT_KEY_BYTES, None)}
  }
  /// The entry value encoded as bytes via FlatMsg (empty for tombstones).
  #[inline]
  pub fn value_bytes(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(LiveTableMessage::VT_VALUE_BYTES, None)}
  }
  /// Optional version that must be current for this mutation to apply (0 = none).
  #[inline]
  pub fn expected_version(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(LiveTableMessage::VT_EXPECTED_VERSION, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for LiveTableMessage<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("mutation_id", Self::VT_MUTATION_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("key_bytes", Self::VT_KEY_BYTES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("value_bytes", Self::VT_VALUE_BYTES, false)?
     .visit_field::<u64>("expected_version", Self::VT_EXPECTED_VERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct LiveTableMessageArgs<'a> {
    pub mutation_id: u64,
    pub key_bytes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub value_bytes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub expected_version: u64,
}
impl<'a> Default for LiveTableMessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    LiveTableMessageArgs {
      mutation_id: 0,
      key_bytes: None,
      value_bytes: None,
      expected_version: 0,
    }
  }
}

pub struct LiveTableMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LiveTableMessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_mutation_id(&mut self, mutation_id: u64) {
    self.fbb_.push_slot::<u64>(LiveTableMessage::VT_MUTATION_ID, mutation_id, 0);
  }
  #[inline]
  pub fn add_key_bytes(&mut self, key_bytes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LiveTableMessage::VT_KEY_BYTES, key_bytes);
  }
  #[inline]
  pub fn add_value_bytes(&mut self, value_bytes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LiveTableMessage::VT_VALUE_BYTES, value_bytes);
  }
  #[inline]
  pub fn add_expected_version(&mut self, expected_version: u64) {
    self.fbb_.push_slot::<u64>(LiveTableMessage::VT_EXPECTED_VERSION, expected_version, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LiveTableMessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LiveTableMessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LiveTableMessage<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LiveTableMessage<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LiveTableMessage");
      ds.field("mutation_id", &self.mutation_id());
      ds.field("key_bytes", &self.key_bytes());
      ds.field("value_bytes", &self.value_bytes());
      ds.field("expected_version", &self.expected_version());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `LiveTableMessage`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_live_table_message_unchecked`.
pub fn root_as_live_table_message(buf: &[u8]) -> Result<LiveTableMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<LiveTableMessage>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `LiveTableMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_live_table_message_unchecked`.
pub fn size_prefixed_root_as_live_table_message(buf: &[u8]) -> Result<LiveTableMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<LiveTableMessage>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `LiveTableMessage` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_live_table_message_unchecked`.
pub fn root_as_live_table_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LiveTableMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<LiveTableMessage<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `LiveTableMessage` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_live_table_message_unchecked`.
pub fn size_prefixed_root_as_live_table_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LiveTableMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<LiveTableMessage<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a LiveTableMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `LiveTableMessage`.
pub unsafe fn root_as_live_table_message_unchecked(buf: &[u8]) -> LiveTableMessage<'_> {
  unsafe { ::flatbuffers::root_unchecked::<LiveTableMessage>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed LiveTableMessage and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `LiveTableMessage`.
pub unsafe fn size_prefixed_root_as_live_table_message_unchecked(buf: &[u8]) -> LiveTableMessage<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<LiveTableMessage>(buf) }
}
#[inline]
pub fn finish_live_table_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<LiveTableMessage<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_live_table_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<LiveTableMessage<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
