// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum SchedulerRequestOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct SchedulerRequest<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for SchedulerRequest<'a> {
type Inner = SchedulerRequest<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> SchedulerRequest<'a> {
pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 6;
pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 8;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
SchedulerRequest { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args SchedulerRequestArgs<'args>
) -> ::flatbuffers::WIPOffset<SchedulerRequest<'bldr>> {
let mut builder = SchedulerRequestBuilder::new(_fbb);
builder.add_replicas(args.replicas);
if let Some(x) = args.workload_id { builder.add_workload_id(x); }
builder.add_variant(args.variant);
builder.finish()
}
#[inline]
pub fn variant(&self) -> u8 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u8>(SchedulerRequest::VT_VARIANT, Some(0)).unwrap()}
}
#[inline]
pub fn workload_id(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SchedulerRequest::VT_WORKLOAD_ID, None)}
}
#[inline]
pub fn replicas(&self) -> u32 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u32>(SchedulerRequest::VT_REPLICAS, Some(0)).unwrap()}
}
}
impl ::flatbuffers::Verifiable for SchedulerRequest<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
 .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
 .finish();
Ok(())
}
}
pub struct SchedulerRequestArgs<'a> {
pub variant: u8,
pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
pub replicas: u32,
}
impl<'a> Default for SchedulerRequestArgs<'a> {
#[inline]
fn default() -> Self {
SchedulerRequestArgs {
  variant: 0,
  workload_id: None,
  replicas: 0,
}
}
}
pub struct SchedulerRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SchedulerRequestBuilder<'a, 'b, A> {
#[inline]
pub fn add_variant(&mut self, variant: u8) {
self.fbb_.push_slot::<u8>(SchedulerRequest::VT_VARIANT, variant, 0);
}
#[inline]
pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SchedulerRequest::VT_WORKLOAD_ID, workload_id);
}
#[inline]
pub fn add_replicas(&mut self, replicas: u32) {
self.fbb_.push_slot::<u32>(SchedulerRequest::VT_REPLICAS, replicas, 0);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SchedulerRequestBuilder<'a, 'b, A> {
let start = _fbb.start_table();
SchedulerRequestBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<SchedulerRequest<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for SchedulerRequest<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("SchedulerRequest");
  ds.field("variant", &self.variant());
  ds.field("workload_id", &self.workload_id());
  ds.field("replicas", &self.replicas());
  ds.finish()
}
}
pub enum SchedulerResponseOffset {}
#[derive(Copy, Clone, PartialEq)]
pub struct SchedulerResponse<'a> {
pub _tab: ::flatbuffers::Table<'a>,
}
impl<'a> ::flatbuffers::Follow<'a> for SchedulerResponse<'a> {
type Inner = SchedulerResponse<'a>;
#[inline]
unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
}
}
impl<'a> SchedulerResponse<'a> {
pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
pub const VT_REASON: ::flatbuffers::VOffsetT = 6;
#[inline]
pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
SchedulerResponse { _tab: table }
}
#[allow(unused_mut)]
pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
_fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
args: &'args SchedulerResponseArgs<'args>
) -> ::flatbuffers::WIPOffset<SchedulerResponse<'bldr>> {
let mut builder = SchedulerResponseBuilder::new(_fbb);
if let Some(x) = args.reason { builder.add_reason(x); }
builder.add_variant(args.variant);
builder.finish()
}
#[inline]
pub fn variant(&self) -> u8 {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<u8>(SchedulerResponse::VT_VARIANT, Some(0)).unwrap()}
}
#[inline]
pub fn reason(&self) -> Option<&'a str> {
// Safety:
// Created from valid Table for this object
// which contains a valid value in this slot
unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SchedulerResponse::VT_REASON, None)}
}
}
impl ::flatbuffers::Verifiable for SchedulerResponse<'_> {
#[inline]
fn run_verifier(
v: &mut ::flatbuffers::Verifier, pos: usize
) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
v.visit_table(pos)?
 .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
 .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("reason", Self::VT_REASON, false)?
 .finish();
Ok(())
}
}
pub struct SchedulerResponseArgs<'a> {
pub variant: u8,
pub reason: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for SchedulerResponseArgs<'a> {
#[inline]
fn default() -> Self {
SchedulerResponseArgs {
  variant: 0,
  reason: None,
}
}
}
pub struct SchedulerResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SchedulerResponseBuilder<'a, 'b, A> {
#[inline]
pub fn add_variant(&mut self, variant: u8) {
self.fbb_.push_slot::<u8>(SchedulerResponse::VT_VARIANT, variant, 0);
}
#[inline]
pub fn add_reason(&mut self, reason: ::flatbuffers::WIPOffset<&'b  str>) {
self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SchedulerResponse::VT_REASON, reason);
}
#[inline]
pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SchedulerResponseBuilder<'a, 'b, A> {
let start = _fbb.start_table();
SchedulerResponseBuilder {
  fbb_: _fbb,
  start_: start,
}
}
#[inline]
pub fn finish(self) -> ::flatbuffers::WIPOffset<SchedulerResponse<'a>> {
let o = self.fbb_.end_table(self.start_);
::flatbuffers::WIPOffset::new(o.value())
}
}
impl ::core::fmt::Debug for SchedulerResponse<'_> {
fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
let mut ds = f.debug_struct("SchedulerResponse");
  ds.field("variant", &self.variant());
  ds.field("reason", &self.reason());
  ds.finish()
}
}
#[inline]
/// Verifies that a buffer of bytes contains a `SchedulerRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scheduler_request_unchecked`.
pub fn root_as_scheduler_request(buf: &[u8]) -> Result<SchedulerRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::root::<SchedulerRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `SchedulerRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_scheduler_request_unchecked`.
pub fn size_prefixed_root_as_scheduler_request(buf: &[u8]) -> Result<SchedulerRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::size_prefixed_root::<SchedulerRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `SchedulerRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scheduler_request_unchecked`.
pub fn root_as_scheduler_request_with_opts<'b, 'o>(
opts: &'o ::flatbuffers::VerifierOptions,
buf: &'b [u8],
) -> Result<SchedulerRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::root_with_opts::<SchedulerRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `SchedulerRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_scheduler_request_unchecked`.
pub fn size_prefixed_root_as_scheduler_request_with_opts<'b, 'o>(
opts: &'o ::flatbuffers::VerifierOptions,
buf: &'b [u8],
) -> Result<SchedulerRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
::flatbuffers::size_prefixed_root_with_opts::<SchedulerRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a SchedulerRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `SchedulerRequest`.
pub unsafe fn root_as_scheduler_request_unchecked(buf: &[u8]) -> SchedulerRequest<'_> {
unsafe { ::flatbuffers::root_unchecked::<SchedulerRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed SchedulerRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `SchedulerRequest`.
pub unsafe fn size_prefixed_root_as_scheduler_request_unchecked(buf: &[u8]) -> SchedulerRequest<'_> {
unsafe { ::flatbuffers::size_prefixed_root_unchecked::<SchedulerRequest>(buf) }
}
#[inline]
pub fn finish_scheduler_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
root: ::flatbuffers::WIPOffset<SchedulerRequest<'a>>) {
fbb.finish(root, None);
}
#[inline]
pub fn finish_size_prefixed_scheduler_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<SchedulerRequest<'a>>) {
fbb.finish_size_prefixed(root, None);
}
