// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EchoRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EchoRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EchoRequest<'a> {
  type Inner = EchoRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EchoRequest<'a> {
  pub const VT_RESPONSE_CHANNEL: ::flatbuffers::VOffsetT = 4;
  pub const VT_MSG: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EchoRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EchoRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EchoRequest<'bldr>> {
    let mut builder = EchoRequestBuilder::new(_fbb);
    builder.add_response_channel(args.response_channel);
    if let Some(x) = args.msg { builder.add_msg(x); }
    builder.finish()
  }


  /// Directory entry where the caller has registered a shared response channel.
  #[inline]
  pub fn response_channel(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(EchoRequest::VT_RESPONSE_CHANNEL, Some(0)).unwrap()}
  }
  /// Payload to echo back to the caller.
  #[inline]
  pub fn msg(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EchoRequest::VT_MSG, None)}
  }
}

impl ::flatbuffers::Verifiable for EchoRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("response_channel", Self::VT_RESPONSE_CHANNEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("msg", Self::VT_MSG, false)?
     .finish();
    Ok(())
  }
}
pub struct EchoRequestArgs<'a> {
    pub response_channel: u64,
    pub msg: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EchoRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    EchoRequestArgs {
      response_channel: 0,
      msg: None,
    }
  }
}

pub struct EchoRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EchoRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_response_channel(&mut self, response_channel: u64) {
    self.fbb_.push_slot::<u64>(EchoRequest::VT_RESPONSE_CHANNEL, response_channel, 0);
  }
  #[inline]
  pub fn add_msg(&mut self, msg: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EchoRequest::VT_MSG, msg);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EchoRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EchoRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EchoRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EchoRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EchoRequest");
      ds.field("response_channel", &self.response_channel());
      ds.field("msg", &self.msg());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EchoRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_request_unchecked`.
pub fn root_as_echo_request(buf: &[u8]) -> Result<EchoRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<EchoRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EchoRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_echo_request_unchecked`.
pub fn size_prefixed_root_as_echo_request(buf: &[u8]) -> Result<EchoRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<EchoRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EchoRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_request_unchecked`.
pub fn root_as_echo_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EchoRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<EchoRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EchoRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_request_unchecked`.
pub fn size_prefixed_root_as_echo_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EchoRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<EchoRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EchoRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EchoRequest`.
pub unsafe fn root_as_echo_request_unchecked(buf: &[u8]) -> EchoRequest<'_> {
  unsafe { ::flatbuffers::root_unchecked::<EchoRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EchoRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EchoRequest`.
pub unsafe fn size_prefixed_root_as_echo_request_unchecked(buf: &[u8]) -> EchoRequest<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<EchoRequest>(buf) }
}
pub const ECHO_REQUEST_IDENTIFIER: &str = "ECHO";

#[inline]
pub fn echo_request_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ECHO_REQUEST_IDENTIFIER, false)
}

#[inline]
pub fn echo_request_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ECHO_REQUEST_IDENTIFIER, true)
}

#[inline]
pub fn finish_echo_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<EchoRequest<'a>>) {
  fbb.finish(root, Some(ECHO_REQUEST_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_echo_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<EchoRequest<'a>>) {
  fbb.finish_size_prefixed(root, Some(ECHO_REQUEST_IDENTIFIER));
}
