// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for Atlas Flatbuffers namespaces.
pub mod atlas {
  use super::*;
  pub mod protocol {
    use super::*;
    mod atlas_message_generated;
    pub use self::atlas_message_generated::*;
    mod atlas_payload_generated;
    pub use self::atlas_payload_generated::*;
    mod error_response_generated;
    pub use self::error_response_generated::*;
    mod get_request_generated;
    pub use self::get_request_generated::*;
    mod get_response_generated;
    pub use self::get_response_generated::*;
    mod insert_request_generated;
    pub use self::insert_request_generated::*;
    mod lookup_request_generated;
    pub use self::lookup_request_generated::*;
    mod lookup_response_generated;
    pub use self::lookup_response_generated::*;
    mod ok_response_generated;
    pub use self::ok_response_generated::*;
    mod remove_request_generated;
    pub use self::remove_request_generated::*;
    mod remove_response_generated;
    pub use self::remove_response_generated::*;
  }
  pub mod uri {
    use super::*;
    mod uri_generated;
    pub use self::uri_generated::*;
  }
}
