// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum PipeControlOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Per-stream pipe-control message.
///
/// Variant tag values:
///   0 = Handshake { uri }
///   1 = Accepted
///   2 = Terminate { code }
pub struct PipeControl<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PipeControl<'a> {
  type Inner = PipeControl<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PipeControl<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_URI: ::flatbuffers::VOffsetT = 6;
  pub const VT_CODE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PipeControl { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PipeControlArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PipeControl<'bldr>> {
    let mut builder = PipeControlBuilder::new(_fbb);
    builder.add_code(args.code);
    if let Some(x) = args.uri { builder.add_uri(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  /// Variant discriminator.
  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(PipeControl::VT_VARIANT, Some(0)).unwrap()}
  }
  /// Discovery URI of the fabric channel to bridge (Handshake variant).
  #[inline]
  pub fn uri(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PipeControl::VT_URI, None)}
  }
  /// Machine-readable termination code (Terminate variant).
  #[inline]
  pub fn code(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(PipeControl::VT_CODE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for PipeControl<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
     .visit_field::<u32>("code", Self::VT_CODE, false)?
     .finish();
    Ok(())
  }
}
pub struct PipeControlArgs<'a> {
    pub variant: u8,
    pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub code: u32,
}
impl<'a> Default for PipeControlArgs<'a> {
  #[inline]
  fn default() -> Self {
    PipeControlArgs {
      variant: 0,
      uri: None,
      code: 0,
    }
  }
}

pub struct PipeControlBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PipeControlBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(PipeControl::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PipeControl::VT_URI, uri);
  }
  #[inline]
  pub fn add_code(&mut self, code: u32) {
    self.fbb_.push_slot::<u32>(PipeControl::VT_CODE, code, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PipeControlBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PipeControlBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PipeControl<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PipeControl<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PipeControl");
      ds.field("variant", &self.variant());
      ds.field("uri", &self.uri());
      ds.field("code", &self.code());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `PipeControl`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pipe_control_unchecked`.
pub fn root_as_pipe_control(buf: &[u8]) -> Result<PipeControl<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<PipeControl>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `PipeControl` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_pipe_control_unchecked`.
pub fn size_prefixed_root_as_pipe_control(buf: &[u8]) -> Result<PipeControl<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<PipeControl>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `PipeControl` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pipe_control_unchecked`.
pub fn root_as_pipe_control_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<PipeControl<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<PipeControl<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `PipeControl` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pipe_control_unchecked`.
pub fn size_prefixed_root_as_pipe_control_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<PipeControl<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<PipeControl<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a PipeControl and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `PipeControl`.
pub unsafe fn root_as_pipe_control_unchecked(buf: &[u8]) -> PipeControl<'_> {
  unsafe { ::flatbuffers::root_unchecked::<PipeControl>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed PipeControl and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `PipeControl`.
pub unsafe fn size_prefixed_root_as_pipe_control_unchecked(buf: &[u8]) -> PipeControl<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<PipeControl>(buf) }
}
#[inline]
pub fn finish_pipe_control_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<PipeControl<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_pipe_control_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<PipeControl<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
