// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ControlRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ControlRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ControlRequest<'a> {
  type Inner = ControlRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ControlRequest<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 8;
  pub const VT_MODULE: ::flatbuffers::VOffsetT = 10;
  pub const VT_URI: ::flatbuffers::VOffsetT = 12;
  pub const VT_MANIFEST: ::flatbuffers::VOffsetT = 14;
  pub const VT_BYTES: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ControlRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ControlRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ControlRequest<'bldr>> {
    let mut builder = ControlRequestBuilder::new(_fbb);
    if let Some(x) = args.bytes { builder.add_bytes(x); }
    if let Some(x) = args.manifest { builder.add_manifest(x); }
    if let Some(x) = args.uri { builder.add_uri(x); }
    if let Some(x) = args.module { builder.add_module(x); }
    builder.add_replicas(args.replicas);
    if let Some(x) = args.workload_id { builder.add_workload_id(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ControlRequest::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn workload_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_WORKLOAD_ID, None)}
  }
  #[inline]
  pub fn replicas(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ControlRequest::VT_REPLICAS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn module(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_MODULE, None)}
  }
  #[inline]
  pub fn uri(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_URI, None)}
  }
  #[inline]
  pub fn manifest(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlRequest::VT_MANIFEST, None)}
  }
  #[inline]
  pub fn bytes(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ControlRequest::VT_BYTES, None)}
  }
}

impl ::flatbuffers::Verifiable for ControlRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
     .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("module", Self::VT_MODULE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("manifest", Self::VT_MANIFEST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("bytes", Self::VT_BYTES, false)?
     .finish();
    Ok(())
  }
}
pub struct ControlRequestArgs<'a> {
    pub variant: u8,
    pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub replicas: u32,
    pub module: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub manifest: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub bytes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for ControlRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    ControlRequestArgs {
      variant: 0,
      workload_id: None,
      replicas: 0,
      module: None,
      uri: None,
      manifest: None,
      bytes: None,
    }
  }
}

pub struct ControlRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ControlRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(ControlRequest::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_WORKLOAD_ID, workload_id);
  }
  #[inline]
  pub fn add_replicas(&mut self, replicas: u32) {
    self.fbb_.push_slot::<u32>(ControlRequest::VT_REPLICAS, replicas, 0);
  }
  #[inline]
  pub fn add_module(&mut self, module: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_MODULE, module);
  }
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_URI, uri);
  }
  #[inline]
  pub fn add_manifest(&mut self, manifest: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_MANIFEST, manifest);
  }
  #[inline]
  pub fn add_bytes(&mut self, bytes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlRequest::VT_BYTES, bytes);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ControlRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ControlRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ControlRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ControlRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ControlRequest");
      ds.field("variant", &self.variant());
      ds.field("workload_id", &self.workload_id());
      ds.field("replicas", &self.replicas());
      ds.field("module", &self.module());
      ds.field("uri", &self.uri());
      ds.field("manifest", &self.manifest());
      ds.field("bytes", &self.bytes());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ControlRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn root_as_control_request(buf: &[u8]) -> Result<ControlRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ControlRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ControlRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_control_request_unchecked`.
pub fn size_prefixed_root_as_control_request(buf: &[u8]) -> Result<ControlRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ControlRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ControlRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn root_as_control_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ControlRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ControlRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ControlRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_control_request_unchecked`.
pub fn size_prefixed_root_as_control_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ControlRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ControlRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ControlRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ControlRequest`.
pub unsafe fn root_as_control_request_unchecked(buf: &[u8]) -> ControlRequest<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ControlRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ControlRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ControlRequest`.
pub unsafe fn size_prefixed_root_as_control_request_unchecked(buf: &[u8]) -> ControlRequest<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ControlRequest>(buf) }
}
#[inline]
pub fn finish_control_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ControlRequest<'a>>) {
  fbb.finish(root, None);
}
#[inline]
pub fn finish_size_prefixed_control_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ControlRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
