// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ControlResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ControlResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ControlResponse<'a> {
  type Inner = ControlResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ControlResponse<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_MANIFEST: ::flatbuffers::VOffsetT = 6;
  pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 8;
  pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 10;
  pub const VT_MODULE: ::flatbuffers::VOffsetT = 12;
  pub const VT_DELEGATED: ::flatbuffers::VOffsetT = 14;
  pub const VT_DEPLOYMENT: ::flatbuffers::VOffsetT = 16;
  pub const VT_STEP: ::flatbuffers::VOffsetT = 18;
  pub const VT_CONTEXT: ::flatbuffers::VOffsetT = 20;
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 22;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ControlResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ControlResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ControlResponse<'bldr>> {
    let mut builder = ControlResponseBuilder::new(_fbb);
    if let Some(x) = args.target { builder.add_target(x); }
    if let Some(x) = args.context { builder.add_context(x); }
    if let Some(x) = args.step { builder.add_step(x); }
    if let Some(x) = args.deployment { builder.add_deployment(x); }
    if let Some(x) = args.delegated { builder.add_delegated(x); }
    if let Some(x) = args.module { builder.add_module(x); }
    builder.add_replicas(args.replicas);
    if let Some(x) = args.workload_id { builder.add_workload_id(x); }
    if let Some(x) = args.manifest { builder.add_manifest(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(ControlResponse::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn manifest(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_MANIFEST, None)}
  }
  #[inline]
  pub fn workload_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_WORKLOAD_ID, None)}
  }
  #[inline]
  pub fn replicas(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ControlResponse::VT_REPLICAS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn module(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_MODULE, None)}
  }
  #[inline]
  pub fn delegated(&self) -> Option<DelegationStatus<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<DelegationStatus>>(ControlResponse::VT_DELEGATED, None)}
  }
  #[inline]
  pub fn deployment(&self) -> Option<Deployment<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Deployment>>(ControlResponse::VT_DEPLOYMENT, None)}
  }
  #[inline]
  pub fn step(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_STEP, None)}
  }
  #[inline]
  pub fn context(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ControlResponse::VT_CONTEXT, None)}
  }
  #[inline]
  pub fn target(&self) -> Option<ResolvedTarget<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ResolvedTarget>>(ControlResponse::VT_TARGET, None)}
  }
}

impl ::flatbuffers::Verifiable for ControlResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("manifest", Self::VT_MANIFEST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
     .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("module", Self::VT_MODULE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<DelegationStatus>>("delegated", Self::VT_DELEGATED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Deployment>>("deployment", Self::VT_DEPLOYMENT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("step", Self::VT_STEP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("context", Self::VT_CONTEXT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ResolvedTarget>>("target", Self::VT_TARGET, false)?
     .finish();
    Ok(())
  }
}
pub struct ControlResponseArgs<'a> {
    pub variant: u8,
    pub manifest: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub replicas: u32,
    pub module: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub delegated: Option<::flatbuffers::WIPOffset<DelegationStatus<'a>>>,
    pub deployment: Option<::flatbuffers::WIPOffset<Deployment<'a>>>,
    pub step: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub context: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub target: Option<::flatbuffers::WIPOffset<ResolvedTarget<'a>>>,
}
impl<'a> Default for ControlResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    ControlResponseArgs {
      variant: 0,
      manifest: None,
      workload_id: None,
      replicas: 0,
      module: None,
      delegated: None,
      deployment: None,
      step: None,
      context: None,
      target: None,
    }
  }
}

pub struct ControlResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ControlResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(ControlResponse::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_manifest(&mut self, manifest: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_MANIFEST, manifest);
  }
  #[inline]
  pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_WORKLOAD_ID, workload_id);
  }
  #[inline]
  pub fn add_replicas(&mut self, replicas: u32) {
    self.fbb_.push_slot::<u32>(ControlResponse::VT_REPLICAS, replicas, 0);
  }
  #[inline]
  pub fn add_module(&mut self, module: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_MODULE, module);
  }
  #[inline]
  pub fn add_delegated(&mut self, delegated: ::flatbuffers::WIPOffset<DelegationStatus<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<DelegationStatus>>(ControlResponse::VT_DELEGATED, delegated);
  }
  #[inline]
  pub fn add_deployment(&mut self, deployment: ::flatbuffers::WIPOffset<Deployment<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Deployment>>(ControlResponse::VT_DEPLOYMENT, deployment);
  }
  #[inline]
  pub fn add_step(&mut self, step: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_STEP, step);
  }
  #[inline]
  pub fn add_context(&mut self, context: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ControlResponse::VT_CONTEXT, context);
  }
  #[inline]
  pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<ResolvedTarget<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ResolvedTarget>>(ControlResponse::VT_TARGET, target);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ControlResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ControlResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ControlResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ControlResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ControlResponse");
      ds.field("variant", &self.variant());
      ds.field("manifest", &self.manifest());
      ds.field("workload_id", &self.workload_id());
      ds.field("replicas", &self.replicas());
      ds.field("module", &self.module());
      ds.field("delegated", &self.delegated());
      ds.field("deployment", &self.deployment());
      ds.field("step", &self.step());
      ds.field("context", &self.context());
      ds.field("target", &self.target());
      ds.finish()
  }
}
