// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DelegationStatusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DelegationStatus<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DelegationStatus<'a> {
  type Inner = DelegationStatus<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DelegationStatus<'a> {
  pub const VT_STEP: ::flatbuffers::VOffsetT = 4;
  pub const VT_APPLIED: ::flatbuffers::VOffsetT = 6;
  pub const VT_CONTEXT: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DelegationStatus { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DelegationStatusArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DelegationStatus<'bldr>> {
    let mut builder = DelegationStatusBuilder::new(_fbb);
    if let Some(x) = args.context { builder.add_context(x); }
    if let Some(x) = args.step { builder.add_step(x); }
    builder.add_applied(args.applied);
    builder.finish()
  }


  #[inline]
  pub fn step(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DelegationStatus::VT_STEP, None)}
  }
  #[inline]
  pub fn applied(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DelegationStatus::VT_APPLIED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn context(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DelegationStatus::VT_CONTEXT, None)}
  }
}

impl ::flatbuffers::Verifiable for DelegationStatus<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("step", Self::VT_STEP, false)?
     .visit_field::<bool>("applied", Self::VT_APPLIED, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("context", Self::VT_CONTEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct DelegationStatusArgs<'a> {
    pub step: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub applied: bool,
    pub context: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DelegationStatusArgs<'a> {
  #[inline]
  fn default() -> Self {
    DelegationStatusArgs {
      step: None,
      applied: false,
      context: None,
    }
  }
}

pub struct DelegationStatusBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DelegationStatusBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_step(&mut self, step: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DelegationStatus::VT_STEP, step);
  }
  #[inline]
  pub fn add_applied(&mut self, applied: bool) {
    self.fbb_.push_slot::<bool>(DelegationStatus::VT_APPLIED, applied, false);
  }
  #[inline]
  pub fn add_context(&mut self, context: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DelegationStatus::VT_CONTEXT, context);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DelegationStatusBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DelegationStatusBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DelegationStatus<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DelegationStatus<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DelegationStatus");
      ds.field("step", &self.step());
      ds.field("applied", &self.applied());
      ds.field("context", &self.context());
      ds.finish()
  }
}
