// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DeploymentOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Deployment<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Deployment<'a> {
  type Inner = Deployment<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Deployment<'a> {
  pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_REPLICAS: ::flatbuffers::VOffsetT = 6;
  pub const VT_MODULE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Deployment { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DeploymentArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Deployment<'bldr>> {
    let mut builder = DeploymentBuilder::new(_fbb);
    if let Some(x) = args.module { builder.add_module(x); }
    builder.add_replicas(args.replicas);
    if let Some(x) = args.workload_id { builder.add_workload_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn workload_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Deployment::VT_WORKLOAD_ID, None)}
  }
  #[inline]
  pub fn replicas(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Deployment::VT_REPLICAS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn module(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Deployment::VT_MODULE, None)}
  }
}

impl ::flatbuffers::Verifiable for Deployment<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
     .visit_field::<u32>("replicas", Self::VT_REPLICAS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("module", Self::VT_MODULE, false)?
     .finish();
    Ok(())
  }
}
pub struct DeploymentArgs<'a> {
    pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub replicas: u32,
    pub module: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DeploymentArgs<'a> {
  #[inline]
  fn default() -> Self {
    DeploymentArgs {
      workload_id: None,
      replicas: 0,
      module: None,
    }
  }
}

pub struct DeploymentBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DeploymentBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Deployment::VT_WORKLOAD_ID, workload_id);
  }
  #[inline]
  pub fn add_replicas(&mut self, replicas: u32) {
    self.fbb_.push_slot::<u32>(Deployment::VT_REPLICAS, replicas, 0);
  }
  #[inline]
  pub fn add_module(&mut self, module: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Deployment::VT_MODULE, module);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DeploymentBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DeploymentBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Deployment<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Deployment<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Deployment");
      ds.field("workload_id", &self.workload_id());
      ds.field("replicas", &self.replicas());
      ds.field("module", &self.module());
      ds.finish()
  }
}
