// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DesiredStateRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DesiredStateRecord<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DesiredStateRecord<'a> {
  type Inner = DesiredStateRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DesiredStateRecord<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_DEPLOYMENT: ::flatbuffers::VOffsetT = 6;
  pub const VT_PIPELINE: ::flatbuffers::VOffsetT = 8;
  pub const VT_WORKLOAD_ID: ::flatbuffers::VOffsetT = 10;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DesiredStateRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DesiredStateRecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DesiredStateRecord<'bldr>> {
    let mut builder = DesiredStateRecordBuilder::new(_fbb);
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    if let Some(x) = args.workload_id { builder.add_workload_id(x); }
    if let Some(x) = args.pipeline { builder.add_pipeline(x); }
    if let Some(x) = args.deployment { builder.add_deployment(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(DesiredStateRecord::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn deployment(&self) -> Option<Deployment<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Deployment>>(DesiredStateRecord::VT_DEPLOYMENT, None)}
  }
  #[inline]
  pub fn pipeline(&self) -> Option<PipelineBinding<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<PipelineBinding>>(DesiredStateRecord::VT_PIPELINE, None)}
  }
  #[inline]
  pub fn workload_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DesiredStateRecord::VT_WORKLOAD_ID, None)}
  }
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DesiredStateRecord::VT_TENANT, None)}
  }
}

impl ::flatbuffers::Verifiable for DesiredStateRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Deployment>>("deployment", Self::VT_DEPLOYMENT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<PipelineBinding>>("pipeline", Self::VT_PIPELINE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("workload_id", Self::VT_WORKLOAD_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .finish();
    Ok(())
  }
}
pub struct DesiredStateRecordArgs<'a> {
    pub variant: u8,
    pub deployment: Option<::flatbuffers::WIPOffset<Deployment<'a>>>,
    pub pipeline: Option<::flatbuffers::WIPOffset<PipelineBinding<'a>>>,
    pub workload_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DesiredStateRecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    DesiredStateRecordArgs {
      variant: 0,
      deployment: None,
      pipeline: None,
      workload_id: None,
      tenant: None,
    }
  }
}

pub struct DesiredStateRecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DesiredStateRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(DesiredStateRecord::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_deployment(&mut self, deployment: ::flatbuffers::WIPOffset<Deployment<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Deployment>>(DesiredStateRecord::VT_DEPLOYMENT, deployment);
  }
  #[inline]
  pub fn add_pipeline(&mut self, pipeline: ::flatbuffers::WIPOffset<PipelineBinding<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<PipelineBinding>>(DesiredStateRecord::VT_PIPELINE, pipeline);
  }
  #[inline]
  pub fn add_workload_id(&mut self, workload_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DesiredStateRecord::VT_WORKLOAD_ID, workload_id);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DesiredStateRecord::VT_TENANT, tenant);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DesiredStateRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DesiredStateRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DesiredStateRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DesiredStateRecord<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DesiredStateRecord");
      ds.field("variant", &self.variant());
      ds.field("deployment", &self.deployment());
      ds.field("pipeline", &self.pipeline());
      ds.field("workload_id", &self.workload_id());
      ds.field("tenant", &self.tenant());
      ds.finish()
  }
}
