// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum PipelineBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PipelineBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PipelineBinding<'a> {
  type Inner = PipelineBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PipelineBinding<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_FROM: ::flatbuffers::VOffsetT = 6;
  pub const VT_TO: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PipelineBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PipelineBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PipelineBinding<'bldr>> {
    let mut builder = PipelineBindingBuilder::new(_fbb);
    if let Some(x) = args.to { builder.add_to(x); }
    if let Some(x) = args.from { builder.add_from(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PipelineBinding::VT_NAME, None)}
  }
  #[inline]
  pub fn from(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PipelineBinding::VT_FROM, None)}
  }
  #[inline]
  pub fn to(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PipelineBinding::VT_TO, None)}
  }
}

impl ::flatbuffers::Verifiable for PipelineBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("from", Self::VT_FROM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("to", Self::VT_TO, false)?
     .finish();
    Ok(())
  }
}
pub struct PipelineBindingArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub from: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub to: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PipelineBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    PipelineBindingArgs {
      name: None,
      from: None,
      to: None,
    }
  }
}

pub struct PipelineBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PipelineBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PipelineBinding::VT_NAME, name);
  }
  #[inline]
  pub fn add_from(&mut self, from: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PipelineBinding::VT_FROM, from);
  }
  #[inline]
  pub fn add_to(&mut self, to: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PipelineBinding::VT_TO, to);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PipelineBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PipelineBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PipelineBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PipelineBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PipelineBinding");
      ds.field("name", &self.name());
      ds.field("from", &self.from());
      ds.field("to", &self.to());
      ds.finish()
  }
}
