// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum ResolvedTargetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ResolvedTarget<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ResolvedTarget<'a> {
  type Inner = ResolvedTarget<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ResolvedTarget<'a> {
  pub const VT_URI: ::flatbuffers::VOffsetT = 4;
  pub const VT_HOST_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_RESOURCE_ID: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ResolvedTarget { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ResolvedTargetArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ResolvedTarget<'bldr>> {
    let mut builder = ResolvedTargetBuilder::new(_fbb);
    builder.add_resource_id(args.resource_id);
    if let Some(x) = args.host_id { builder.add_host_id(x); }
    if let Some(x) = args.uri { builder.add_uri(x); }
    builder.finish()
  }


  #[inline]
  pub fn uri(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ResolvedTarget::VT_URI, None)}
  }
  #[inline]
  pub fn host_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ResolvedTarget::VT_HOST_ID, None)}
  }
  #[inline]
  pub fn resource_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ResolvedTarget::VT_RESOURCE_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ResolvedTarget<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("uri", Self::VT_URI, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("host_id", Self::VT_HOST_ID, false)?
     .visit_field::<u64>("resource_id", Self::VT_RESOURCE_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ResolvedTargetArgs<'a> {
    pub uri: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub host_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub resource_id: u64,
}
impl<'a> Default for ResolvedTargetArgs<'a> {
  #[inline]
  fn default() -> Self {
    ResolvedTargetArgs {
      uri: None,
      host_id: None,
      resource_id: 0,
    }
  }
}

pub struct ResolvedTargetBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ResolvedTargetBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_uri(&mut self, uri: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ResolvedTarget::VT_URI, uri);
  }
  #[inline]
  pub fn add_host_id(&mut self, host_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ResolvedTarget::VT_HOST_ID, host_id);
  }
  #[inline]
  pub fn add_resource_id(&mut self, resource_id: u64) {
    self.fbb_.push_slot::<u64>(ResolvedTarget::VT_RESOURCE_ID, resource_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ResolvedTargetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ResolvedTargetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ResolvedTarget<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ResolvedTarget<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ResolvedTarget");
      ds.field("uri", &self.uri());
      ds.field("host_id", &self.host_id());
      ds.field("resource_id", &self.resource_id());
      ds.finish()
  }
}
