// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum IdentityResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IdentityResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IdentityResponse<'a> {
  type Inner = IdentityResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> IdentityResponse<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 6;
  pub const VT_CERTIFICATE_DER: ::flatbuffers::VOffsetT = 8;
  pub const VT_FINGERPRINT: ::flatbuffers::VOffsetT = 10;
  pub const VT_STEP: ::flatbuffers::VOffsetT = 12;
  pub const VT_CONTEXT: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    IdentityResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IdentityResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<IdentityResponse<'bldr>> {
    let mut builder = IdentityResponseBuilder::new(_fbb);
    if let Some(x) = args.context { builder.add_context(x); }
    if let Some(x) = args.step { builder.add_step(x); }
    if let Some(x) = args.fingerprint { builder.add_fingerprint(x); }
    if let Some(x) = args.certificate_der { builder.add_certificate_der(x); }
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(IdentityResponse::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(IdentityResponse::VT_TENANT, None)}
  }
  #[inline]
  pub fn certificate_der(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(IdentityResponse::VT_CERTIFICATE_DER, None)}
  }
  #[inline]
  pub fn fingerprint(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(IdentityResponse::VT_FINGERPRINT, None)}
  }
  #[inline]
  pub fn step(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(IdentityResponse::VT_STEP, None)}
  }
  #[inline]
  pub fn context(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(IdentityResponse::VT_CONTEXT, None)}
  }
}

impl ::flatbuffers::Verifiable for IdentityResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("certificate_der", Self::VT_CERTIFICATE_DER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("fingerprint", Self::VT_FINGERPRINT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("step", Self::VT_STEP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("context", Self::VT_CONTEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct IdentityResponseArgs<'a> {
    pub variant: u8,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub certificate_der: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub fingerprint: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub step: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub context: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for IdentityResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    IdentityResponseArgs {
      variant: 0,
      tenant: None,
      certificate_der: None,
      fingerprint: None,
      step: None,
      context: None,
    }
  }
}

pub struct IdentityResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IdentityResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(IdentityResponse::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityResponse::VT_TENANT, tenant);
  }
  #[inline]
  pub fn add_certificate_der(&mut self, certificate_der: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityResponse::VT_CERTIFICATE_DER, certificate_der);
  }
  #[inline]
  pub fn add_fingerprint(&mut self, fingerprint: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityResponse::VT_FINGERPRINT, fingerprint);
  }
  #[inline]
  pub fn add_step(&mut self, step: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityResponse::VT_STEP, step);
  }
  #[inline]
  pub fn add_context(&mut self, context: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityResponse::VT_CONTEXT, context);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> IdentityResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IdentityResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<IdentityResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for IdentityResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("IdentityResponse");
      ds.field("variant", &self.variant());
      ds.field("tenant", &self.tenant());
      ds.field("certificate_der", &self.certificate_der());
      ds.field("fingerprint", &self.fingerprint());
      ds.field("step", &self.step());
      ds.field("context", &self.context());
      ds.finish()
  }
}
