// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;

pub enum IdentityRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IdentityRequest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IdentityRequest<'a> {
  type Inner = IdentityRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> IdentityRequest<'a> {
  pub const VT_VARIANT: ::flatbuffers::VOffsetT = 4;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 6;
  pub const VT_SPKI_DER: ::flatbuffers::VOffsetT = 8;
  pub const VT_FINGERPRINT: ::flatbuffers::VOffsetT = 10;
  pub const VT_GRANTS: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    IdentityRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IdentityRequestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<IdentityRequest<'bldr>> {
    let mut builder = IdentityRequestBuilder::new(_fbb);
    if let Some(x) = args.grants { builder.add_grants(x); }
    if let Some(x) = args.fingerprint { builder.add_fingerprint(x); }
    if let Some(x) = args.spki_der { builder.add_spki_der(x); }
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    builder.add_variant(args.variant);
    builder.finish()
  }


  #[inline]
  pub fn variant(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(IdentityRequest::VT_VARIANT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(IdentityRequest::VT_TENANT, None)}
  }
  #[inline]
  pub fn spki_der(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(IdentityRequest::VT_SPKI_DER, None)}
  }
  #[inline]
  pub fn fingerprint(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(IdentityRequest::VT_FINGERPRINT, None)}
  }
  #[inline]
  pub fn grants(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(IdentityRequest::VT_GRANTS, None)}
  }
}

impl ::flatbuffers::Verifiable for IdentityRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("variant", Self::VT_VARIANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("spki_der", Self::VT_SPKI_DER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("fingerprint", Self::VT_FINGERPRINT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("grants", Self::VT_GRANTS, false)?
     .finish();
    Ok(())
  }
}
pub struct IdentityRequestArgs<'a> {
    pub variant: u8,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub spki_der: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub fingerprint: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub grants: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for IdentityRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    IdentityRequestArgs {
      variant: 0,
      tenant: None,
      spki_der: None,
      fingerprint: None,
      grants: None,
    }
  }
}

pub struct IdentityRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IdentityRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_variant(&mut self, variant: u8) {
    self.fbb_.push_slot::<u8>(IdentityRequest::VT_VARIANT, variant, 0);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityRequest::VT_TENANT, tenant);
  }
  #[inline]
  pub fn add_spki_der(&mut self, spki_der: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityRequest::VT_SPKI_DER, spki_der);
  }
  #[inline]
  pub fn add_fingerprint(&mut self, fingerprint: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityRequest::VT_FINGERPRINT, fingerprint);
  }
  #[inline]
  pub fn add_grants(&mut self, grants: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdentityRequest::VT_GRANTS, grants);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> IdentityRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IdentityRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<IdentityRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for IdentityRequest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("IdentityRequest");
      ds.field("variant", &self.variant());
      ds.field("tenant", &self.tenant());
      ds.field("spki_der", &self.spki_der());
      ds.field("fingerprint", &self.fingerprint());
      ds.field("grants", &self.grants());
      ds.finish()
  }
}

#[inline]
/// Verifies that a buffer of bytes contains a `IdentityRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_identity_request_unchecked`.
pub fn root_as_identity_request(buf: &[u8]) -> Result<IdentityRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<IdentityRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `IdentityRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_identity_request_unchecked`.
pub fn size_prefixed_root_as_identity_request(buf: &[u8]) -> Result<IdentityRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<IdentityRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `IdentityRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_identity_request_unchecked`.
pub fn root_as_identity_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IdentityRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<IdentityRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `IdentityRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_identity_request_unchecked`.
pub fn size_prefixed_root_as_identity_request_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<IdentityRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<IdentityRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a IdentityRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `IdentityRequest`.
pub unsafe fn root_as_identity_request_unchecked(buf: &[u8]) -> IdentityRequest<'_> {
  unsafe { ::flatbuffers::root_unchecked::<IdentityRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed IdentityRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `IdentityRequest`.
pub unsafe fn size_prefixed_root_as_identity_request_unchecked(buf: &[u8]) -> IdentityRequest<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<IdentityRequest>(buf) }
}
#[inline]
pub fn finish_identity_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<IdentityRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_identity_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<IdentityRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
