// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod examples {
  use super::*;
  pub mod echo {
    use super::*;
    mod echo_request_generated;
    pub use self::echo_request_generated::*;
    mod echo_response_generated;
    pub use self::echo_response_generated::*;
  } // echo
} // examples
