// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum AuditRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Audit record emitted for every request.
pub struct AuditRecord<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AuditRecord<'a> {
  type Inner = AuditRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AuditRecord<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_VERDICT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AuditRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AuditRecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<AuditRecord<'bldr>> {
    let mut builder = AuditRecordBuilder::new(_fbb);
    builder.add_request_id(args.request_id);
    if let Some(x) = args.verdict { builder.add_verdict(x); }
    builder.finish()
  }


  /// Request identifier.
  #[inline]
  pub fn request_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AuditRecord::VT_REQUEST_ID, Some(0)).unwrap()}
  }
  /// Verdict summary.
  #[inline]
  pub fn verdict(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(AuditRecord::VT_VERDICT, None)}
  }
}

impl ::flatbuffers::Verifiable for AuditRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("verdict", Self::VT_VERDICT, false)?
     .finish();
    Ok(())
  }
}
pub struct AuditRecordArgs<'a> {
    pub request_id: u64,
    pub verdict: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for AuditRecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    AuditRecordArgs {
      request_id: 0,
      verdict: None,
    }
  }
}

pub struct AuditRecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AuditRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: u64) {
    self.fbb_.push_slot::<u64>(AuditRecord::VT_REQUEST_ID, request_id, 0);
  }
  #[inline]
  pub fn add_verdict(&mut self, verdict: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(AuditRecord::VT_VERDICT, verdict);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AuditRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AuditRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AuditRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AuditRecord<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AuditRecord");
      ds.field("request_id", &self.request_id());
      ds.field("verdict", &self.verdict());
      ds.finish()
  }
}
