// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum HttpRequestMetaOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Minimal HTTP request metadata captured at the edge.
pub struct HttpRequestMeta<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for HttpRequestMeta<'a> {
  type Inner = HttpRequestMeta<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> HttpRequestMeta<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_METHOD: ::flatbuffers::VOffsetT = 6;
  pub const VT_PATH: ::flatbuffers::VOffsetT = 8;
  pub const VT_CLIENT_IP: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    HttpRequestMeta { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args HttpRequestMetaArgs<'args>
  ) -> ::flatbuffers::WIPOffset<HttpRequestMeta<'bldr>> {
    let mut builder = HttpRequestMetaBuilder::new(_fbb);
    builder.add_request_id(args.request_id);
    if let Some(x) = args.client_ip { builder.add_client_ip(x); }
    if let Some(x) = args.path { builder.add_path(x); }
    if let Some(x) = args.method { builder.add_method(x); }
    builder.finish()
  }


  /// Request identifier.
  #[inline]
  pub fn request_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(HttpRequestMeta::VT_REQUEST_ID, Some(0)).unwrap()}
  }
  /// HTTP method.
  #[inline]
  pub fn method(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(HttpRequestMeta::VT_METHOD, None)}
  }
  /// Request path.
  #[inline]
  pub fn path(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(HttpRequestMeta::VT_PATH, None)}
  }
  /// Client IP address.
  #[inline]
  pub fn client_ip(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(HttpRequestMeta::VT_CLIENT_IP, None)}
  }
}

impl ::flatbuffers::Verifiable for HttpRequestMeta<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("method", Self::VT_METHOD, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("path", Self::VT_PATH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("client_ip", Self::VT_CLIENT_IP, false)?
     .finish();
    Ok(())
  }
}
pub struct HttpRequestMetaArgs<'a> {
    pub request_id: u64,
    pub method: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub path: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub client_ip: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for HttpRequestMetaArgs<'a> {
  #[inline]
  fn default() -> Self {
    HttpRequestMetaArgs {
      request_id: 0,
      method: None,
      path: None,
      client_ip: None,
    }
  }
}

pub struct HttpRequestMetaBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HttpRequestMetaBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: u64) {
    self.fbb_.push_slot::<u64>(HttpRequestMeta::VT_REQUEST_ID, request_id, 0);
  }
  #[inline]
  pub fn add_method(&mut self, method: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(HttpRequestMeta::VT_METHOD, method);
  }
  #[inline]
  pub fn add_path(&mut self, path: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(HttpRequestMeta::VT_PATH, path);
  }
  #[inline]
  pub fn add_client_ip(&mut self, client_ip: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(HttpRequestMeta::VT_CLIENT_IP, client_ip);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> HttpRequestMetaBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    HttpRequestMetaBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<HttpRequestMeta<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for HttpRequestMeta<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("HttpRequestMeta");
      ds.field("request_id", &self.request_id());
      ds.field("method", &self.method());
      ds.field("path", &self.path());
      ds.field("client_ip", &self.client_ip());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `HttpRequestMeta`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_http_request_meta_unchecked`.
pub fn root_as_http_request_meta(buf: &[u8]) -> Result<HttpRequestMeta<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<HttpRequestMeta>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `HttpRequestMeta` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_http_request_meta_unchecked`.
pub fn size_prefixed_root_as_http_request_meta(buf: &[u8]) -> Result<HttpRequestMeta<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<HttpRequestMeta>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `HttpRequestMeta` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_http_request_meta_unchecked`.
pub fn root_as_http_request_meta_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<HttpRequestMeta<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<HttpRequestMeta<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `HttpRequestMeta` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_http_request_meta_unchecked`.
pub fn size_prefixed_root_as_http_request_meta_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<HttpRequestMeta<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<HttpRequestMeta<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a HttpRequestMeta and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `HttpRequestMeta`.
pub unsafe fn root_as_http_request_meta_unchecked(buf: &[u8]) -> HttpRequestMeta<'_> {
  unsafe { ::flatbuffers::root_unchecked::<HttpRequestMeta>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed HttpRequestMeta and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `HttpRequestMeta`.
pub unsafe fn size_prefixed_root_as_http_request_meta_unchecked(buf: &[u8]) -> HttpRequestMeta<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<HttpRequestMeta>(buf) }
}
pub const HTTP_REQUEST_META_IDENTIFIER: &str = "WAFR";

#[inline]
pub fn http_request_meta_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, HTTP_REQUEST_META_IDENTIFIER, false)
}

#[inline]
pub fn http_request_meta_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, HTTP_REQUEST_META_IDENTIFIER, true)
}

#[inline]
pub fn finish_http_request_meta_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<HttpRequestMeta<'a>>) {
  fbb.finish(root, Some(HTTP_REQUEST_META_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_http_request_meta_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<HttpRequestMeta<'a>>) {
  fbb.finish_size_prefixed(root, Some(HTTP_REQUEST_META_IDENTIFIER));
}
