// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum SecurityAlertOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Alert emitted for suspicious traffic.
pub struct SecurityAlert<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SecurityAlert<'a> {
  type Inner = SecurityAlert<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SecurityAlert<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_SUMMARY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SecurityAlert { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SecurityAlertArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SecurityAlert<'bldr>> {
    let mut builder = SecurityAlertBuilder::new(_fbb);
    builder.add_request_id(args.request_id);
    if let Some(x) = args.summary { builder.add_summary(x); }
    builder.finish()
  }


  /// Request identifier.
  #[inline]
  pub fn request_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SecurityAlert::VT_REQUEST_ID, Some(0)).unwrap()}
  }
  /// Human-readable summary.
  #[inline]
  pub fn summary(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SecurityAlert::VT_SUMMARY, None)}
  }
}

impl ::flatbuffers::Verifiable for SecurityAlert<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("summary", Self::VT_SUMMARY, false)?
     .finish();
    Ok(())
  }
}
pub struct SecurityAlertArgs<'a> {
    pub request_id: u64,
    pub summary: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for SecurityAlertArgs<'a> {
  #[inline]
  fn default() -> Self {
    SecurityAlertArgs {
      request_id: 0,
      summary: None,
    }
  }
}

pub struct SecurityAlertBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SecurityAlertBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: u64) {
    self.fbb_.push_slot::<u64>(SecurityAlert::VT_REQUEST_ID, request_id, 0);
  }
  #[inline]
  pub fn add_summary(&mut self, summary: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SecurityAlert::VT_SUMMARY, summary);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SecurityAlertBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SecurityAlertBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SecurityAlert<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SecurityAlert<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SecurityAlert");
      ds.field("request_id", &self.request_id());
      ds.field("summary", &self.summary());
      ds.finish()
  }
}
