// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum VerdictOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Verdict produced by edge screening.
pub struct Verdict<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Verdict<'a> {
  type Inner = Verdict<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Verdict<'a> {
  pub const VT_REQUEST_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_DECISION: ::flatbuffers::VOffsetT = 6;
  pub const VT_REASON: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Verdict { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args VerdictArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Verdict<'bldr>> {
    let mut builder = VerdictBuilder::new(_fbb);
    builder.add_request_id(args.request_id);
    if let Some(x) = args.reason { builder.add_reason(x); }
    if let Some(x) = args.decision { builder.add_decision(x); }
    builder.finish()
  }


  /// Request identifier.
  #[inline]
  pub fn request_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Verdict::VT_REQUEST_ID, Some(0)).unwrap()}
  }
  /// Decision outcome (allow or block).
  #[inline]
  pub fn decision(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Verdict::VT_DECISION, None)}
  }
  /// Decision rationale.
  #[inline]
  pub fn reason(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Verdict::VT_REASON, None)}
  }
}

impl ::flatbuffers::Verifiable for Verdict<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("decision", Self::VT_DECISION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("reason", Self::VT_REASON, false)?
     .finish();
    Ok(())
  }
}
pub struct VerdictArgs<'a> {
    pub request_id: u64,
    pub decision: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub reason: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for VerdictArgs<'a> {
  #[inline]
  fn default() -> Self {
    VerdictArgs {
      request_id: 0,
      decision: None,
      reason: None,
    }
  }
}

pub struct VerdictBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> VerdictBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: u64) {
    self.fbb_.push_slot::<u64>(Verdict::VT_REQUEST_ID, request_id, 0);
  }
  #[inline]
  pub fn add_decision(&mut self, decision: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Verdict::VT_DECISION, decision);
  }
  #[inline]
  pub fn add_reason(&mut self, reason: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Verdict::VT_REASON, reason);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> VerdictBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    VerdictBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Verdict<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Verdict<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Verdict");
      ds.field("request_id", &self.request_id());
      ds.field("decision", &self.decision());
      ds.field("reason", &self.reason());
      ds.finish()
  }
}
