[package]
name = "selium-supervisor"
version.workspace = true
edition.workspace = true
description = "Selium supervisor system guest"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
selium-guest.workspace = true

[lints]
workspace = true
