// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum LogRecordOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LogRecord<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for LogRecord<'a> {
  type Inner = LogRecord<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LogRecord<'a> {
  pub const VT_LEVEL: ::flatbuffers::VOffsetT = 4;
  pub const VT_TARGET: ::flatbuffers::VOffsetT = 6;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 8;
  pub const VT_FIELDS: ::flatbuffers::VOffsetT = 10;
  pub const VT_SPANS: ::flatbuffers::VOffsetT = 12;
  pub const VT_TIMESTAMP_MS: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    LogRecord { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LogRecordArgs<'args>
  ) -> ::flatbuffers::WIPOffset<LogRecord<'bldr>> {
    let mut builder = LogRecordBuilder::new(_fbb);
    builder.add_timestamp_ms(args.timestamp_ms);
    if let Some(x) = args.spans { builder.add_spans(x); }
    if let Some(x) = args.fields { builder.add_fields(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.target { builder.add_target(x); }
    builder.add_level(args.level);
    builder.finish()
  }


  #[inline]
  pub fn level(&self) -> LogLevel {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LogLevel>(LogRecord::VT_LEVEL, Some(LogLevel::Trace)).unwrap()}
  }
  #[inline]
  pub fn target(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LogRecord::VT_TARGET, None)}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(LogRecord::VT_MESSAGE, None)}
  }
  #[inline]
  pub fn fields(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field>>>>(LogRecord::VT_FIELDS, None)}
  }
  #[inline]
  pub fn spans(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Span<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Span>>>>(LogRecord::VT_SPANS, None)}
  }
  #[inline]
  pub fn timestamp_ms(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(LogRecord::VT_TIMESTAMP_MS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for LogRecord<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<LogLevel>("level", Self::VT_LEVEL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("target", Self::VT_TARGET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Field>>>>("fields", Self::VT_FIELDS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Span>>>>("spans", Self::VT_SPANS, false)?
     .visit_field::<u64>("timestamp_ms", Self::VT_TIMESTAMP_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct LogRecordArgs<'a> {
    pub level: LogLevel,
    pub target: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub fields: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Field<'a>>>>>,
    pub spans: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Span<'a>>>>>,
    pub timestamp_ms: u64,
}
impl<'a> Default for LogRecordArgs<'a> {
  #[inline]
  fn default() -> Self {
    LogRecordArgs {
      level: LogLevel::Trace,
      target: None,
      message: None,
      fields: None,
      spans: None,
      timestamp_ms: 0,
    }
  }
}

pub struct LogRecordBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LogRecordBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_level(&mut self, level: LogLevel) {
    self.fbb_.push_slot::<LogLevel>(LogRecord::VT_LEVEL, level, LogLevel::Trace);
  }
  #[inline]
  pub fn add_target(&mut self, target: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_TARGET, target);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_fields(&mut self, fields: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Field<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_FIELDS, fields);
  }
  #[inline]
  pub fn add_spans(&mut self, spans: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Span<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(LogRecord::VT_SPANS, spans);
  }
  #[inline]
  pub fn add_timestamp_ms(&mut self, timestamp_ms: u64) {
    self.fbb_.push_slot::<u64>(LogRecord::VT_TIMESTAMP_MS, timestamp_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LogRecordBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LogRecordBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<LogRecord<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for LogRecord<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("LogRecord");
      ds.field("level", &self.level());
      ds.field("target", &self.target());
      ds.field("message", &self.message());
      ds.field("fields", &self.fields());
      ds.field("spans", &self.spans());
      ds.field("timestamp_ms", &self.timestamp_ms());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `LogRecord`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_record_unchecked`.
pub fn root_as_log_record(buf: &[u8]) -> Result<LogRecord<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<LogRecord>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `LogRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_log_record_unchecked`.
pub fn size_prefixed_root_as_log_record(buf: &[u8]) -> Result<LogRecord<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<LogRecord>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `LogRecord` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_record_unchecked`.
pub fn root_as_log_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LogRecord<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<LogRecord<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `LogRecord` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_log_record_unchecked`.
pub fn size_prefixed_root_as_log_record_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<LogRecord<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<LogRecord<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a LogRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `LogRecord`.
pub unsafe fn root_as_log_record_unchecked(buf: &[u8]) -> LogRecord<'_> {
  unsafe { ::flatbuffers::root_unchecked::<LogRecord>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed LogRecord and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `LogRecord`.
pub unsafe fn size_prefixed_root_as_log_record_unchecked(buf: &[u8]) -> LogRecord<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<LogRecord>(buf) }
}
pub const LOG_RECORD_IDENTIFIER: &str = "SLOG";

#[inline]
pub fn log_record_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, LOG_RECORD_IDENTIFIER, false)
}

#[inline]
pub fn log_record_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, LOG_RECORD_IDENTIFIER, true)
}

#[inline]
pub fn finish_log_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<LogRecord<'a>>) {
  fbb.finish(root, Some(LOG_RECORD_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_log_record_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<LogRecord<'a>>) {
  fbb.finish_size_prefixed(root, Some(LOG_RECORD_IDENTIFIER));
}
