// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum WarningOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Warning<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Warning<'a> {
  type Inner = Warning<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Warning<'a> {
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Warning { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WarningArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Warning<'bldr>> {
    let mut builder = WarningBuilder::new(_fbb);
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }


  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Warning::VT_MESSAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for Warning<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct WarningArgs<'a> {
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for WarningArgs<'a> {
  #[inline]
  fn default() -> Self {
    WarningArgs {
      message: None,
    }
  }
}

pub struct WarningBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WarningBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Warning::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> WarningBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WarningBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Warning<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Warning<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Warning");
      ds.field("message", &self.message());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Warning`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_warning_unchecked`.
pub fn root_as_warning(buf: &[u8]) -> Result<Warning<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Warning>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Warning` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_warning_unchecked`.
pub fn size_prefixed_root_as_warning(buf: &[u8]) -> Result<Warning<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Warning>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Warning` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_warning_unchecked`.
pub fn root_as_warning_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Warning<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Warning<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Warning` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_warning_unchecked`.
pub fn size_prefixed_root_as_warning_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Warning<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Warning<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Warning and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Warning`.
pub unsafe fn root_as_warning_unchecked(buf: &[u8]) -> Warning<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Warning>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Warning and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Warning`.
pub unsafe fn size_prefixed_root_as_warning_unchecked(buf: &[u8]) -> Warning<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Warning>(buf) }
}
pub const WARNING_IDENTIFIER: &str = "LOGA";

#[inline]
pub fn warning_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, WARNING_IDENTIFIER, false)
}

#[inline]
pub fn warning_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, WARNING_IDENTIFIER, true)
}

#[inline]
pub fn finish_warning_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Warning<'a>>) {
  fbb.finish(root, Some(WARNING_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_warning_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Warning<'a>>) {
  fbb.finish_size_prefixed(root, Some(WARNING_IDENTIFIER));
}
