// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod examples {
  use super::*;
  pub mod echo {
    use super::*;
    mod echo_msg_generated;
    pub use self::echo_msg_generated::*;
  } // echo
} // examples
