// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EchoMsgOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EchoMsg<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EchoMsg<'a> {
  type Inner = EchoMsg<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EchoMsg<'a> {
  pub const VT_MSG: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EchoMsg { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EchoMsgArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EchoMsg<'bldr>> {
    let mut builder = EchoMsgBuilder::new(_fbb);
    if let Some(x) = args.msg { builder.add_msg(x); }
    builder.finish()
  }


  /// The payload.
  #[inline]
  pub fn msg(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EchoMsg::VT_MSG, None)}
  }
}

impl ::flatbuffers::Verifiable for EchoMsg<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("msg", Self::VT_MSG, false)?
     .finish();
    Ok(())
  }
}
pub struct EchoMsgArgs<'a> {
    pub msg: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EchoMsgArgs<'a> {
  #[inline]
  fn default() -> Self {
    EchoMsgArgs {
      msg: None,
    }
  }
}

pub struct EchoMsgBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EchoMsgBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_msg(&mut self, msg: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EchoMsg::VT_MSG, msg);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EchoMsgBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EchoMsgBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EchoMsg<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EchoMsg<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EchoMsg");
      ds.field("msg", &self.msg());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `EchoMsg`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_msg_unchecked`.
pub fn root_as_echo_msg(buf: &[u8]) -> Result<EchoMsg<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<EchoMsg>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `EchoMsg` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_echo_msg_unchecked`.
pub fn size_prefixed_root_as_echo_msg(buf: &[u8]) -> Result<EchoMsg<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<EchoMsg>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `EchoMsg` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_msg_unchecked`.
pub fn root_as_echo_msg_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EchoMsg<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<EchoMsg<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `EchoMsg` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_echo_msg_unchecked`.
pub fn size_prefixed_root_as_echo_msg_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<EchoMsg<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<EchoMsg<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a EchoMsg and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `EchoMsg`.
pub unsafe fn root_as_echo_msg_unchecked(buf: &[u8]) -> EchoMsg<'_> {
  unsafe { ::flatbuffers::root_unchecked::<EchoMsg>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed EchoMsg and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `EchoMsg`.
pub unsafe fn size_prefixed_root_as_echo_msg_unchecked(buf: &[u8]) -> EchoMsg<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<EchoMsg>(buf) }
}
pub const ECHO_MSG_IDENTIFIER: &str = "ECHO";

#[inline]
pub fn echo_msg_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ECHO_MSG_IDENTIFIER, false)
}

#[inline]
pub fn echo_msg_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, ECHO_MSG_IDENTIFIER, true)
}

#[inline]
pub fn finish_echo_msg_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<EchoMsg<'a>>) {
  fbb.finish(root, Some(ECHO_MSG_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_echo_msg_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<EchoMsg<'a>>) {
  fbb.finish_size_prefixed(root, Some(ECHO_MSG_IDENTIFIER));
}
