// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum EchoResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct EchoResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for EchoResponse<'a> {
  type Inner = EchoResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> EchoResponse<'a> {
  pub const VT_MSG: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    EchoResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args EchoResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<EchoResponse<'bldr>> {
    let mut builder = EchoResponseBuilder::new(_fbb);
    if let Some(x) = args.msg { builder.add_msg(x); }
    builder.finish()
  }


  /// The echoed payload.
  #[inline]
  pub fn msg(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(EchoResponse::VT_MSG, None)}
  }
}

impl ::flatbuffers::Verifiable for EchoResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("msg", Self::VT_MSG, false)?
     .finish();
    Ok(())
  }
}
pub struct EchoResponseArgs<'a> {
    pub msg: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for EchoResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    EchoResponseArgs {
      msg: None,
    }
  }
}

pub struct EchoResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EchoResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_msg(&mut self, msg: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(EchoResponse::VT_MSG, msg);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> EchoResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    EchoResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<EchoResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for EchoResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("EchoResponse");
      ds.field("msg", &self.msg());
      ds.finish()
  }
}
