[package]
name = "selium-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4.0"
proc-macro2 = "1.0.66"
quote = "1.0.32"
rhai = { version = "1.15.1", features = ["sync"] }
selium-common = { version = "0.1", path = "../common" }
syn = "2.0.28"
