[package]
name = "selium-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4"
proc-macro2 = "1.0"
quote = "1.0"
rhai = { version = "1.15", features = ["sync"] }
selium-common = { version = "0.1", path = "../common" }
syn = "2.0"
