// Automatically generated by build.rs. Do not modify manually.
// Combined module tree for Selium Flatbuffers namespaces.
pub mod selium {
  use super::*;
  pub mod logging {
    use super::*;
    mod field_generated;
    pub use self::field_generated::*;
    mod log_level_generated;
    pub use self::log_level_generated::*;
    mod log_record_generated;
    pub use self::log_record_generated::*;
    mod span_generated;
    pub use self::span_generated::*;
  }
  pub mod result {
    use super::*;
    mod flat_result_generated;
    pub use self::flat_result_generated::*;
  }
}
