// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum DomainEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A single advisory domain-to-tenant mapping.
pub struct DomainEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DomainEntry<'a> {
  type Inner = DomainEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DomainEntry<'a> {
  pub const VT_DOMAIN: ::flatbuffers::VOffsetT = 4;
  pub const VT_TENANT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DomainEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DomainEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DomainEntry<'bldr>> {
    let mut builder = DomainEntryBuilder::new(_fbb);
    if let Some(x) = args.tenant { builder.add_tenant(x); }
    if let Some(x) = args.domain { builder.add_domain(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> DomainEntryT {
    let domain = self.domain().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let tenant = self.tenant().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    DomainEntryT {
      domain,
      tenant,
    }
  }

  /// Domain (e.g. `example.com`).
  #[inline]
  pub fn domain(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DomainEntry::VT_DOMAIN, None)}
  }
  /// Tenant the domain maps to (e.g. `acme`).
  #[inline]
  pub fn tenant(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DomainEntry::VT_TENANT, None)}
  }
}

impl ::flatbuffers::Verifiable for DomainEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("domain", Self::VT_DOMAIN, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("tenant", Self::VT_TENANT, false)?
     .finish();
    Ok(())
  }
}
pub struct DomainEntryArgs<'a> {
    pub domain: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub tenant: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DomainEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    DomainEntryArgs {
      domain: None,
      tenant: None,
    }
  }
}

pub struct DomainEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DomainEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_domain(&mut self, domain: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DomainEntry::VT_DOMAIN, domain);
  }
  #[inline]
  pub fn add_tenant(&mut self, tenant: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DomainEntry::VT_TENANT, tenant);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DomainEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DomainEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DomainEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DomainEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DomainEntry");
      ds.field("domain", &self.domain());
      ds.field("tenant", &self.tenant());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct DomainEntryT {
  pub domain: Option<alloc::string::String>,
  pub tenant: Option<alloc::string::String>,
}
impl Default for DomainEntryT {
  fn default() -> Self {
    Self {
      domain: None,
      tenant: None,
    }
  }
}
impl DomainEntryT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<DomainEntry<'b>> {
    let domain = self.domain.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let tenant = self.tenant.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    DomainEntry::create(_fbb, &DomainEntryArgs{
      domain,
      tenant,
    })
  }
}