// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
use super::*;
pub enum InterfaceMetadataOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Interface metadata for a discovered resource.
pub struct InterfaceMetadata<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for InterfaceMetadata<'a> {
  type Inner = InterfaceMetadata<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> InterfaceMetadata<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_METHODS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    InterfaceMetadata { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args InterfaceMetadataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<InterfaceMetadata<'bldr>> {
    let mut builder = InterfaceMetadataBuilder::new(_fbb);
    if let Some(x) = args.methods { builder.add_methods(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> InterfaceMetadataT {
    let name = self.name().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let methods = self.methods().map(|x| {
      x.iter().map(|s| alloc::string::ToString::to_string(s)).collect()
    });
    InterfaceMetadataT {
      name,
      methods,
    }
  }

  /// Interface name.
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(InterfaceMetadata::VT_NAME, None)}
  }
  /// Method names exposed by the interface.
  #[inline]
  pub fn methods(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(InterfaceMetadata::VT_METHODS, None)}
  }
}

impl ::flatbuffers::Verifiable for InterfaceMetadata<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("methods", Self::VT_METHODS, false)?
     .finish();
    Ok(())
  }
}
pub struct InterfaceMetadataArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub methods: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for InterfaceMetadataArgs<'a> {
  #[inline]
  fn default() -> Self {
    InterfaceMetadataArgs {
      name: None,
      methods: None,
    }
  }
}

pub struct InterfaceMetadataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> InterfaceMetadataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(InterfaceMetadata::VT_NAME, name);
  }
  #[inline]
  pub fn add_methods(&mut self, methods: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(InterfaceMetadata::VT_METHODS, methods);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> InterfaceMetadataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    InterfaceMetadataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<InterfaceMetadata<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for InterfaceMetadata<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("InterfaceMetadata");
      ds.field("name", &self.name());
      ds.field("methods", &self.methods());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct InterfaceMetadataT {
  pub name: Option<alloc::string::String>,
  pub methods: Option<alloc::vec::Vec<alloc::string::String>>,
}
impl Default for InterfaceMetadataT {
  fn default() -> Self {
    Self {
      name: None,
      methods: None,
    }
  }
}
impl InterfaceMetadataT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<InterfaceMetadata<'b>> {
    let name = self.name.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let methods = self.methods.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();_fbb.create_vector(&w)
    });
    InterfaceMetadata::create(_fbb, &InterfaceMetadataArgs{
      name,
      methods,
    })
  }
}