// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod selium {

#[allow(unused_imports, dead_code)]
pub mod dns {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DNS_RECORD_TYPE: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DNS_RECORD_TYPE: u8 = 28;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DNS_RECORD_TYPE: [DnsRecordType; 3] = [
  DnsRecordType::A,
  DnsRecordType::Cname,
  DnsRecordType::Aaaa,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct DnsRecordType(pub u8);
#[allow(non_upper_case_globals)]
impl DnsRecordType {
  pub const A: Self = Self(1);
  pub const Cname: Self = Self(5);
  pub const Aaaa: Self = Self(28);

  pub const ENUM_MIN: u8 = 1;
  pub const ENUM_MAX: u8 = 28;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::A,
    Self::Cname,
    Self::Aaaa,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::A => Some("A"),
      Self::Cname => Some("Cname"),
      Self::Aaaa => Some("Aaaa"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for DnsRecordType {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for DnsRecordType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for DnsRecordType {
    type Output = DnsRecordType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for DnsRecordType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for DnsRecordType {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for DnsRecordType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_DNS_OUTCOME: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_DNS_OUTCOME: u8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_DNS_OUTCOME: [DnsOutcome; 7] = [
  DnsOutcome::Ok,
  DnsOutcome::NxDomain,
  DnsOutcome::Timeout,
  DnsOutcome::Truncated,
  DnsOutcome::ServFail,
  DnsOutcome::Refused,
  DnsOutcome::Upstream,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct DnsOutcome(pub u8);
#[allow(non_upper_case_globals)]
impl DnsOutcome {
  pub const Ok: Self = Self(0);
  pub const NxDomain: Self = Self(1);
  pub const Timeout: Self = Self(2);
  pub const Truncated: Self = Self(3);
  pub const ServFail: Self = Self(4);
  pub const Refused: Self = Self(5);
  pub const Upstream: Self = Self(6);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Ok,
    Self::NxDomain,
    Self::Timeout,
    Self::Truncated,
    Self::ServFail,
    Self::Refused,
    Self::Upstream,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Ok => Some("Ok"),
      Self::NxDomain => Some("NxDomain"),
      Self::Timeout => Some("Timeout"),
      Self::Truncated => Some("Truncated"),
      Self::ServFail => Some("ServFail"),
      Self::Refused => Some("Refused"),
      Self::Upstream => Some("Upstream"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for DnsOutcome {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for DnsOutcome {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for DnsOutcome {
    type Output = DnsOutcome;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for DnsOutcome {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for DnsOutcome {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for DnsOutcome {}
pub enum DnsQueryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DnsQuery<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DnsQuery<'a> {
  type Inner = DnsQuery<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DnsQuery<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_RECORD_TYPE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DnsQuery { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DnsQueryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DnsQuery<'bldr>> {
    let mut builder = DnsQueryBuilder::new(_fbb);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_record_type(args.record_type);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(DnsQuery::VT_NAME, None)}
  }
  #[inline]
  pub fn record_type(&self) -> DnsRecordType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<DnsRecordType>(DnsQuery::VT_RECORD_TYPE, Some(DnsRecordType::A)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for DnsQuery<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<DnsRecordType>("record_type", Self::VT_RECORD_TYPE, false)?
     .finish();
    Ok(())
  }
}
pub struct DnsQueryArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub record_type: DnsRecordType,
}
impl<'a> Default for DnsQueryArgs<'a> {
  #[inline]
  fn default() -> Self {
    DnsQueryArgs {
      name: None,
      record_type: DnsRecordType::A,
    }
  }
}

pub struct DnsQueryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DnsQueryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DnsQuery::VT_NAME, name);
  }
  #[inline]
  pub fn add_record_type(&mut self, record_type: DnsRecordType) {
    self.fbb_.push_slot::<DnsRecordType>(DnsQuery::VT_RECORD_TYPE, record_type, DnsRecordType::A);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DnsQueryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DnsQueryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DnsQuery<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DnsQuery<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DnsQuery");
      ds.field("name", &self.name());
      ds.field("record_type", &self.record_type());
      ds.finish()
  }
}
pub enum DnsResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DnsResponse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DnsResponse<'a> {
  type Inner = DnsResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DnsResponse<'a> {
  pub const VT_OUTCOME: ::flatbuffers::VOffsetT = 4;
  pub const VT_ADDRESSES: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DnsResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DnsResponseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DnsResponse<'bldr>> {
    let mut builder = DnsResponseBuilder::new(_fbb);
    if let Some(x) = args.addresses { builder.add_addresses(x); }
    builder.add_outcome(args.outcome);
    builder.finish()
  }


  #[inline]
  pub fn outcome(&self) -> DnsOutcome {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<DnsOutcome>(DnsResponse::VT_OUTCOME, Some(DnsOutcome::Ok)).unwrap()}
  }
  #[inline]
  pub fn addresses(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(DnsResponse::VT_ADDRESSES, None)}
  }
}

impl ::flatbuffers::Verifiable for DnsResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<DnsOutcome>("outcome", Self::VT_OUTCOME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("addresses", Self::VT_ADDRESSES, false)?
     .finish();
    Ok(())
  }
}
pub struct DnsResponseArgs<'a> {
    pub outcome: DnsOutcome,
    pub addresses: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for DnsResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    DnsResponseArgs {
      outcome: DnsOutcome::Ok,
      addresses: None,
    }
  }
}

pub struct DnsResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DnsResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_outcome(&mut self, outcome: DnsOutcome) {
    self.fbb_.push_slot::<DnsOutcome>(DnsResponse::VT_OUTCOME, outcome, DnsOutcome::Ok);
  }
  #[inline]
  pub fn add_addresses(&mut self, addresses: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DnsResponse::VT_ADDRESSES, addresses);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DnsResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DnsResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DnsResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DnsResponse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DnsResponse");
      ds.field("outcome", &self.outcome());
      ds.field("addresses", &self.addresses());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `DnsQuery`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dns_query_unchecked`.
pub fn root_as_dns_query(buf: &[u8]) -> Result<DnsQuery<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<DnsQuery>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `DnsQuery` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_dns_query_unchecked`.
pub fn size_prefixed_root_as_dns_query(buf: &[u8]) -> Result<DnsQuery<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<DnsQuery>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `DnsQuery` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dns_query_unchecked`.
pub fn root_as_dns_query_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DnsQuery<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<DnsQuery<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `DnsQuery` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dns_query_unchecked`.
pub fn size_prefixed_root_as_dns_query_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DnsQuery<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<DnsQuery<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a DnsQuery and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `DnsQuery`.
pub unsafe fn root_as_dns_query_unchecked(buf: &[u8]) -> DnsQuery<'_> {
  unsafe { ::flatbuffers::root_unchecked::<DnsQuery>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed DnsQuery and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `DnsQuery`.
pub unsafe fn size_prefixed_root_as_dns_query_unchecked(buf: &[u8]) -> DnsQuery<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<DnsQuery>(buf) }
}
#[inline]
pub fn finish_dns_query_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<DnsQuery<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_dns_query_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<DnsQuery<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod dns
}  // pub mod selium

