name: Scheduled Audit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    name: Daily Crate Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Audit crates
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
