name: Draft the release

on:
  push:
    branches:
      - main
      - hotfix

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v7
      - uses: itpetey/breezy@3bf8cebc2034f18908a2086b81e15f06026d6957 # v0.4.1
        with:
          language: rust
